#!/bin/bash
# GOW startup script for Helix Desktop (Hyprland with pipewiresrc)
# EXPERIMENTAL: Uses PipeWire ScreenCast for video capture (not nested Wayland)
set -e

source /opt/gow/bash-lib/utils.sh

gow_log "[start] Starting Helix Desktop (Hyprland with pipewiresrc)..."

# Create symlink to Zed binary if not exists
if [ -f /zed-build/zed ] && [ ! -f /usr/local/bin/zed ]; then
    sudo ln -sf /zed-build/zed /usr/local/bin/zed
    gow_log "[start] Created symlink: /usr/local/bin/zed -> /zed-build/zed"
fi

# Workspace setup
if [ -z "$WORKSPACE_DIR" ]; then
    gow_log "[start] FATAL: WORKSPACE_DIR environment variable not set"
    exit 1
fi
if [ ! -d "$WORKSPACE_DIR" ]; then
    gow_log "[start] FATAL: WORKSPACE_DIR does not exist: $WORKSPACE_DIR"
    exit 1
fi
if [ ! -d /home/retro/work ]; then
    gow_log "[start] FATAL: /home/retro/work bind mount not present"
    exit 1
fi
sudo chown retro:retro "$WORKSPACE_DIR"
sudo chown retro:retro /home/retro/work
gow_log "[start] Workspace mounted at both $WORKSPACE_DIR and /home/retro/work"

# Create Zed config symlinks
WORK_DIR=/home/retro/work
ZED_STATE_DIR=$WORK_DIR/.zed-state
cd /home/retro/work

mkdir -p $ZED_STATE_DIR/config $ZED_STATE_DIR/local-share $ZED_STATE_DIR/cache

rm -rf ~/.config/zed && mkdir -p ~/.config && ln -sf $ZED_STATE_DIR/config ~/.config/zed
rm -rf ~/.local/share/zed && mkdir -p ~/.local/share && ln -sf $ZED_STATE_DIR/local-share ~/.local/share/zed
rm -rf ~/.cache/zed && mkdir -p ~/.cache && ln -sf $ZED_STATE_DIR/cache ~/.cache/zed

gow_log "[start] Zed state symlinks created"

# Configure fontconfig for grayscale antialiasing
mkdir -p ~/.config/fontconfig
cat > ~/.config/fontconfig/fonts.conf << 'FONTCONFIG_EOF'
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="font">
    <edit name="rgba" mode="assign"><const>none</const></edit>
    <edit name="antialias" mode="assign"><bool>true</bool></edit>
    <edit name="hinting" mode="assign"><bool>true</bool></edit>
    <edit name="hintstyle" mode="assign"><const>hintslight</const></edit>
  </match>
</fontconfig>
FONTCONFIG_EOF

# Configure Qwen Code session persistence
export QWEN_DATA_DIR=$WORK_DIR/.qwen-state
mkdir -p $QWEN_DATA_DIR
rm -rf ~/.qwen && ln -sf $QWEN_DATA_DIR ~/.qwen
gow_log "[start] Qwen data directory set: QWEN_DATA_DIR=$QWEN_DATA_DIR"

# Start RevDial client
if [ -n "$HELIX_API_BASE_URL" ] && [ -n "$HELIX_SESSION_ID" ] && [ -n "$USER_API_TOKEN" ]; then
    # Note: RevDial is now integrated into desktop-bridge
    gow_log "[start] Starting RevDial client..."
        -server "$REVDIAL_SERVER" \
        -runner-id "$RUNNER_ID" \
        -token "$USER_API_TOKEN" \
        -local "localhost:9876" \
    gow_log "[start] RevDial client started (PID: $!)"
fi

# Hyprland configuration
export GAMESCOPE_WIDTH=${GAMESCOPE_WIDTH:-1920}
export GAMESCOPE_HEIGHT=${GAMESCOPE_HEIGHT:-1080}
export GAMESCOPE_REFRESH=${GAMESCOPE_REFRESH:-60}

# Hyprland pipewiresrc mode: no WAYLAND_DISPLAY from Wolf
# Hyprland creates its own Wayland socket (wayland-1) for client apps
unset WAYLAND_DISPLAY
gow_log "[start] Hyprland pipewiresrc mode: WAYLAND_DISPLAY unset (using xdg-desktop-portal ScreenCast)"

# Create Hyprland config directory
mkdir -p ~/.config/hypr

# Generate Hyprland config
cat > ~/.config/hypr/hyprland.conf << HYPR_EOF
# Helix Hyprland Configuration (pipewiresrc mode)
# Generated by startup-app.sh

# Monitor configuration (virtual for pipewiresrc)
monitor=,${GAMESCOPE_WIDTH}x${GAMESCOPE_HEIGHT}@${GAMESCOPE_REFRESH},0x0,1

# Execute at launch
exec-once = pipewire &
exec-once = wireplumber &
exec-once = waybar &
exec-once = /opt/gow/start-pipewire-screencast.sh >> /tmp/pipewire-screencast.log 2>&1 &
exec-once = /usr/local/bin/desktop-bridge >> /tmp/desktop-bridge.log 2>&1 &
exec-once = /usr/local/bin/settings-sync-daemon >> /tmp/settings-sync.log 2>&1 &
exec-once = /usr/local/bin/start-zed-helix.sh

# Environment variables
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Input configuration (Alt as modifier - Super captured by macOS/browsers)
input {
    kb_layout = us,gb,fr
    kb_options = caps:ctrl_nocaps
    follow_mouse = 1
    sensitivity = 0
}

# General settings
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(7c3aedee) rgba(a855f7ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

# Decoration
decoration {
    rounding = 8
    blur {
        enabled = true
        size = 3
        passes = 1
    }
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
}

# Animations
animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# Dwindle layout
dwindle {
    pseudotile = yes
    preserve_split = yes
}

# Window rules
windowrulev2 = workspace 1, class:^(dev.zed.Zed-Dev)$
windowrulev2 = workspace 2, class:^(kitty)$
windowrulev2 = workspace 2, class:^(ghostty)$
windowrulev2 = workspace 3, class:^(firefox)$

# Keybindings (Alt as modifier)
\$mod = ALT

bind = \$mod, Return, exec, kitty
bind = \$mod SHIFT, Return, exec, kitty
bind = \$mod SHIFT, Q, killactive
bind = \$mod SHIFT, E, exit
bind = \$mod, V, togglefloating
bind = \$mod, D, exec, fuzzel
bind = \$mod, F, fullscreen
bind = \$mod SHIFT, F, exec, firefox

# Workspace switching
bind = \$mod, 1, workspace, 1
bind = \$mod, 2, workspace, 2
bind = \$mod, 3, workspace, 3
bind = \$mod, 4, workspace, 4

# Move window to workspace
bind = \$mod SHIFT, 1, movetoworkspace, 1
bind = \$mod SHIFT, 2, movetoworkspace, 2
bind = \$mod SHIFT, 3, movetoworkspace, 3
bind = \$mod SHIFT, 4, movetoworkspace, 4

# Focus movement
bind = \$mod, H, movefocus, l
bind = \$mod, L, movefocus, r
bind = \$mod, K, movefocus, u
bind = \$mod, J, movefocus, d

# Window movement
bind = \$mod SHIFT, H, movewindow, l
bind = \$mod SHIFT, L, movewindow, r
bind = \$mod SHIFT, K, movewindow, u
bind = \$mod SHIFT, J, movewindow, d

# Mouse bindings
bindm = \$mod, mouse:272, movewindow
bindm = \$mod, mouse:273, resizewindow

# Wallpaper
exec-once = hyprpaper &

HYPR_EOF

# Create hyprpaper config
cat > ~/.config/hypr/hyprpaper.conf << PAPER_EOF
preload = /usr/share/backgrounds/helix-logo.png
wallpaper = ,/usr/share/backgrounds/helix-logo.png
PAPER_EOF

# Create waybar config for Hyprland
mkdir -p ~/.config/waybar
cat > ~/.config/waybar/config.jsonc << WAYBAR_EOF
{
  "layer": "top",
  "position": "top",
  "height": 30,
  "modules-left": ["hyprland/workspaces", "hyprland/window"],
  "modules-center": [],
  "modules-right": ["cpu", "memory", "clock"],
  "hyprland/workspaces": {
    "format": "{name}",
    "persistent-workspaces": {
      "*": [1, 2, 3, 4]
    }
  },
  "clock": {
    "format": "{:%d %a %H:%M}"
  },
  "cpu": {
    "format": "{usage}% "
  },
  "memory": {
    "format": "{}% "
  }
}
WAYBAR_EOF

cat > ~/.config/waybar/style.css << WAYBAR_CSS
* {
    font-family: "Ubuntu", sans-serif;
    font-size: 14px;
}
window#waybar {
    background-color: rgba(30, 30, 40, 0.95);
    color: #ffffff;
}
#workspaces button {
    padding: 0 8px;
    margin: 2px;
    background-color: #404050;
    color: #888888;
    border-radius: 4px;
}
#workspaces button.active {
    background-color: #7c3aed;
    color: #ffffff;
}
#clock, #cpu, #memory {
    padding: 0 10px;
}
WAYBAR_CSS

gow_log "[start] Hyprland configuration generated"
gow_log "[start] Virtual monitor: ${GAMESCOPE_WIDTH}x${GAMESCOPE_HEIGHT}@${GAMESCOPE_REFRESH}"
gow_log "[start] Starting Hyprland..."

# Start Hyprland with dbus session
dbus-run-session -- Hyprland
