kind: pipeline
type: docker
name: backend

workspace:
  base: /go
  path: src/github.com/helix-ml/helix

steps:
- name: build
  image: golang:1.20-alpine
  commands:
    - go build -o helix
    - go test ./...

---
kind: pipeline
type: exec
name: controlplane-docker-image

platform:
  os: linux
  arch: amd64

steps:
- name: publish-latest
  environment:
    GAR_JSON_KEY:
      from_secret: gar_json_key_b64
  commands:
    - echo $GAR_JSON_KEY | docker login -u _json_key_base64 --password-stdin europe-docker.pkg.dev
    - docker build -f Dockerfile.api --push -t europe-docker.pkg.dev/helixml/helix/controlplane:latest .
  # when:
  #   branch:
  #   - main

depends_on:
- backend

---
kind: pipeline
type: exec
name: frontend-docker-image

platform:
  os: linux
  arch: amd64

steps:
- name: publish-latest
  environment:
    GAR_JSON_KEY:
      from_secret: gar_json_key_b64
  commands:
    - echo $GAR_JSON_KEY | docker login -u _json_key_base64 --password-stdin europe-docker.pkg.dev
    - cd frontend && docker build -f Dockerfile --push -t europe-docker.pkg.dev/helixml/helix/frontend:latest .
  # when:
  #   branch:
  #   - main
