kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/github.com/helix-ml/helix

steps:
- name: build
  image: golang:1.20-alpine
  commands:
    - go build -o helix
- name: unit-test
  image: golang:1.20-alpine
  environment:
    OPENAI_API_KEY:
      from_secret: openai_api_key
    OPENAI_BASE_URL:
      from_secret: openai_base_url
  commands:
    - go test ./...

---
kind: pipeline
type: docker
name: build-controlplane

volumes:
  - name: dockersocket
    host:
      path: /var/run/docker.sock

steps:
- name: publish-image
  image: plugins/gar
  pull: always
  settings:
    dockerfile: Dockerfile
    auto_tag: true
    repo: helixml/helix/controlplane
    location: europe
    json_key:
      from_secret: gar_json_key_b64
  volumes:
  - name: dockersocket
    path: /var/run/docker.sock
  when:
    branch:
    - main
    event:
    - tag
    - push

depends_on:
- default

---
kind: pipeline
type: docker
name: build-frontend

volumes:
  - name: dockersocket
    host:
      path: /var/run/docker.sock

steps:
- name: publish-frontend
  image: plugins/gar
  pull: always
  settings:
    dockerfile: frontend/Dockerfile
    context: frontend
    auto_tag: true
    repo: helixml/helix/frontend
    location: europe
    json_key:
      from_secret: gar_json_key_b64
  volumes:
  - name: dockersocket
    path: /var/run/docker.sock
  when:
    branch:
    - main
    event:
    - tag
    - push

depends_on:
- default

---
kind: pipeline
type: docker
name: build-runner

volumes:
  - name: dockersocket
    host:
      path: /var/run/docker.sock

steps:
- name: publish-runner
  image: plugins/gar
  pull: always
  settings:
    dockerfile: Dockerfile.runner    
    auto_tag: true
    repo: helixml/helix/runner
    location: europe
    json_key:
      from_secret: gar_json_key_b64
  volumes:
  - name: dockersocket
    path: /var/run/docker.sock
  when:
    branch:
    - main
    event:
    - tag
    - push

depends_on:
- default

---
kind: pipeline
type: docker
name: build-unstructured

volumes:
  - name: dockersocket
    host:
      path: /var/run/docker.sock

steps:
- name: publish-unstructured
  image: plugins/gar
  pull: always
  settings:
    dockerfile: unstructured/Dockerfile
    context: unstructured
    auto_tag: true
    repo: helixml/helix/unstructured
    location: europe
    json_key:
      from_secret: gar_json_key_b64
  volumes:
  - name: dockersocket
    path: /var/run/docker.sock
  when:
    branch:
    - main
    event:
    - tag
    - push

depends_on:
- default
