linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - ineffassign
    - gosimple
    - govet
    - misspell
    #- unused
    #- bodyclose
    #- errcheck
    #- prealloc
    #- tparallel
    #- revive

issues:
  deadline: 2m
  exlude-dirs:
    - vendor
