linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - ineffassign
    - gosimple
    - govet
    - misspell
    - unused
    - bodyclose
    - tparallel
    - errcheck
    - revive
    - forbidigo
    # - gocritic

issues:
  exclude-dirs:
    - vendor
    - llama/llama.cpp
  exclude-rules:
    - path: 'api/cmd'
      linters:
        - forbidigo
    - path: 'api/pkg/cli'
      linters:
        - forbidigo
    - path: 'demos'
      linters:
        - forbidigo
    - path: '.*_test.go'
      linters:
        - forbidigo

run:
  timeout: 10m

linters-settings:
  forbidigo:
    forbid:
      - ^fmt\.Print.*
      - ^print(ln)?$
    rules:
      - name: error-strings
        disabled: false
      - name: error-naming
        disabled: false

  gocritic:
    enabled-tags:
      - diagnostic
      - style
