version: "2"

run:
  timeout: 10m

linters:
  enable:
    - staticcheck
    - unconvert
    - ineffassign
    - govet
    - misspell
    - unused
    - bodyclose
    - tparallel
    - errcheck
    - revive
    - forbidigo
    # - gocritic
  exclusions:
    paths:
      - vendor
      - llama/llama.cpp
    rules:
      - path: 'api/cmd'
        linters:
          - forbidigo
      - path: 'api/pkg/cli'
        linters:
          - forbidigo
      - path: 'demos'
        linters:
          - forbidigo
      - path: '.*_test.go'
        linters:
          - forbidigo

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  forbidigo:
    forbid:
      - pattern: ^fmt\.Print.*
      - pattern: ^print(ln)?$

  gocritic:
    enabled-tags:
      - diagnostic
      - style

  revive:
    rules:
      - name: error-strings
        disabled: false
      - name: error-naming
        disabled: false
