linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - ineffassign
    - gosimple
    - govet
    - misspell
    - unused
    - bodyclose
    - tparallel
    - errcheck
    #- revive

issues:
  deadline: 5m
  exlude-dirs:
    - vendor
