# Backend build
FROM golang:1.24 AS go-build-env
WORKDIR /app

# <- COPY go.mod and go.sum files to the workspace
COPY go.mod .
COPY go.sum .

RUN go mod download

# COPY the source code as the last step
COPY api ./api
COPY .git /.git

WORKDIR /app/api

# Install C++ compiler for CGO compilation
RUN apt-get update && apt-get install -y gcc g++ libc6-dev && rm -rf /var/lib/apt/lists/*
# Build the Go app
RUN CGO_ENABLED=1 go build -tags "!rocm" -ldflags "-s -w" -o /helix

FROM alpine:3.21
RUN apk --update add ca-certificates bash openssh unzip wget sqlite

COPY --from=go-build-env /helix /helix

ENTRYPOINT ["/helix", "gptscript"]
