FROM golang:1.20-alpine
WORKDIR /app
RUN apk add --no-cache bash
COPY go.mod go.sum modules.json ./
RUN go mod download
COPY api ./api
WORKDIR /app/api
RUN go build -o /lilysaas
EXPOSE 80
ENTRYPOINT [ "/lilysaas" ]