FROM winglian/axolotl:main-py3.10-cu118-2.0.1@sha256:71582175f32c1aca4f0355b8af62f627429a8a83eabbb84e18096490b1661d3c

WORKDIR /workspace

# Checkout https://github.com/lukemarsden/axolotl/tree/new-long-running (see the hash for the specific version)
RUN cd /workspace/axolotl && \
    git remote rm origin && \
    git remote add lukefork https://github.com/lukemarsden/axolotl && \
    git fetch --all && \
    git checkout 555c7116d58da4ccd742bd2be8dd70680d1056aa

RUN apt-get update -y && apt-get install -y python3 python3-pip git unzip wget python3-virtualenv && \
    git clone https://github.com/lukemarsden/sd-scripts && \
    cd sd-scripts && \
    git checkout long-running && \
    virtualenv venv && \
    . venv/bin/activate && \
    pip install -r requirements.txt && \
    pip install bitsandbytes==0.41.1 && \
    pip install xformers==0.0.22.post4 && \
    pip install scipy==1.11.4 && \
    mkdir sdxl && ( \
        cd sdxl; wget -q --show-progress https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors \
    )

RUN apt-get install -y libgl1-mesa-glx ffmpeg libsm6 libxext6

RUN apt-get install -y software-properties-common && add-apt-repository -y ppa:longsleep/golang-backports && apt update -y && apt install -y golang-1.21 golang-go

RUN mkdir -p /workspace/sd-scripts/output_images

# Fake venv - helix runner expects one but axolotl is the "root venv" (actually, default conda env) in the image
RUN mkdir -p /workspace/axolotl/venv/bin
RUN echo "echo \"Pretending to activate virtualenv (actually doing nothing)\"" > /workspace/axolotl/venv/bin/activate

RUN mkdir -p /workspace/helix
ADD . /workspace/helix/
WORKDIR /workspace/helix
RUN go build -o helix

# TODO: autodetect available GPU memory
ENTRYPOINT ["/workspace/helix/helix", "runner"]
