FROM golang:1.20-alpine
WORKDIR /app
RUN apk add --no-cache bash openssh
COPY go.mod go.sum ./
RUN go mod download
COPY api ./api
WORKDIR /app/api
RUN go build -o /helix
EXPOSE 80
ENTRYPOINT [ "/helix" ]