FROM golang:1.25-alpine3.22
WORKDIR /app
RUN apk add --no-cache bash openssh
COPY go.mod go.sum ./
RUN go mod download
COPY demos ./demos
WORKDIR /app/demos
RUN go build -o /demos
EXPOSE 80
ENTRYPOINT [ "/demos" ]
