FROM typesense/typesense:27.1@sha256:5c12af89130b8ee0be11541321ba8a3a7c7a538d7c6cd95e0409dc2d75ca6455
RUN apt update && apt install -y curl
RUN mkdir -p /models/all-MiniLM-L12-v2 && cd /models/all-MiniLM-L12-v2 && \
    curl -sL -O https://huggingface.co/typesense/models/resolve/main/all-MiniLM-L12-v2/config.json && \
    curl -sL -O https://huggingface.co/typesense/models/resolve/main/all-MiniLM-L12-v2/model.onnx && \
    curl -sL -O https://huggingface.co/typesense/models/resolve/main/all-MiniLM-L12-v2/vocab.txt

COPY scripts/typesense-entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
