FROM typesense/typesense:28.0
RUN apt update && apt install -y curl
RUN mkdir -p /models/all-MiniLM-L12-v2 && cd /models/all-MiniLM-L12-v2 && \
    curl -sL -O https://huggingface.co/typesense/models/resolve/main/all-MiniLM-L12-v2/config.json && \
    curl -sL -O https://huggingface.co/typesense/models/resolve/main/all-MiniLM-L12-v2/model.onnx && \
    curl -sL -O https://huggingface.co/typesense/models/resolve/main/all-MiniLM-L12-v2/vocab.txt

COPY scripts/typesense-entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
