export declare const DARK_GREY = "#666666";
export declare const MIDDLE_GREY = "#999999";
export declare const LIGHT_GREY = "#C8C8FF";
export declare const ORANGE = "#FF5000";
export declare const DARK_ORANGE = "#CC4000";
export declare const ERROR = "#990000";
export declare const COCKROACH_COLOR = "#66cc99";
export declare const POSTGRES_COLOR = "#9966cc";
export declare const AUTOPILOT_COLOR = "#00cc99";
//# sourceMappingURL=colors.d.ts.map