// Code generated by MockGen. DO NOT EDIT.
// Source: api/pkg/external-agent/executor.go
//
// Generated by this command:
//
//	mockgen -source api/pkg/external-agent/executor.go -destination api/pkg/external-agent/executor_mocks.go -package external_agent
//

// Package external_agent is a generated GoMock package.
package external_agent

import (
	context "context"
	reflect "reflect"
	time "time"

	types "github.com/helixml/helix/api/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// CleanupExpiredSessions mocks base method.
func (m *MockExecutor) CleanupExpiredSessions(ctx context.Context, timeout time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CleanupExpiredSessions", ctx, timeout)
}

// CleanupExpiredSessions indicates an expected call of CleanupExpiredSessions.
func (mr *MockExecutorMockRecorder) CleanupExpiredSessions(ctx, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredSessions", reflect.TypeOf((*MockExecutor)(nil).CleanupExpiredSessions), ctx, timeout)
}

// CreateZedThread mocks base method.
func (m *MockExecutor) CreateZedThread(ctx context.Context, instanceID, threadID string, config map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateZedThread", ctx, instanceID, threadID, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateZedThread indicates an expected call of CreateZedThread.
func (mr *MockExecutorMockRecorder) CreateZedThread(ctx, instanceID, threadID, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateZedThread", reflect.TypeOf((*MockExecutor)(nil).CreateZedThread), ctx, instanceID, threadID, config)
}

// FindContainerBySessionID mocks base method.
func (m *MockExecutor) FindContainerBySessionID(ctx context.Context, helixSessionID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindContainerBySessionID", ctx, helixSessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindContainerBySessionID indicates an expected call of FindContainerBySessionID.
func (mr *MockExecutorMockRecorder) FindContainerBySessionID(ctx, helixSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindContainerBySessionID", reflect.TypeOf((*MockExecutor)(nil).FindContainerBySessionID), ctx, helixSessionID)
}

// GetInstanceStatus mocks base method.
func (m *MockExecutor) GetInstanceStatus(instanceID string) (*ZedInstanceStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceStatus", instanceID)
	ret0, _ := ret[0].(*ZedInstanceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceStatus indicates an expected call of GetInstanceStatus.
func (mr *MockExecutorMockRecorder) GetInstanceStatus(instanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceStatus", reflect.TypeOf((*MockExecutor)(nil).GetInstanceStatus), instanceID)
}

// GetSession mocks base method.
func (m *MockExecutor) GetSession(sessionID string) (*ZedSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", sessionID)
	ret0, _ := ret[0].(*ZedSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockExecutorMockRecorder) GetSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockExecutor)(nil).GetSession), sessionID)
}

// HasRunningContainer mocks base method.
func (m *MockExecutor) HasRunningContainer(ctx context.Context, sessionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasRunningContainer", ctx, sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasRunningContainer indicates an expected call of HasRunningContainer.
func (mr *MockExecutorMockRecorder) HasRunningContainer(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasRunningContainer", reflect.TypeOf((*MockExecutor)(nil).HasRunningContainer), ctx, sessionID)
}

// ListInstanceThreads mocks base method.
func (m *MockExecutor) ListInstanceThreads(instanceID string) ([]*ZedThreadInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstanceThreads", instanceID)
	ret0, _ := ret[0].([]*ZedThreadInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstanceThreads indicates an expected call of ListInstanceThreads.
func (mr *MockExecutorMockRecorder) ListInstanceThreads(instanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstanceThreads", reflect.TypeOf((*MockExecutor)(nil).ListInstanceThreads), instanceID)
}

// ListSessions mocks base method.
func (m *MockExecutor) ListSessions() []*ZedSession {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions")
	ret0, _ := ret[0].([]*ZedSession)
	return ret0
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockExecutorMockRecorder) ListSessions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockExecutor)(nil).ListSessions))
}

// StartDesktop mocks base method.
func (m *MockExecutor) StartDesktop(ctx context.Context, agent *types.DesktopAgent) (*types.DesktopAgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDesktop", ctx, agent)
	ret0, _ := ret[0].(*types.DesktopAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartDesktop indicates an expected call of StartDesktop.
func (mr *MockExecutorMockRecorder) StartDesktop(ctx, agent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDesktop", reflect.TypeOf((*MockExecutor)(nil).StartDesktop), ctx, agent)
}

// StartZedInstance mocks base method.
func (m *MockExecutor) StartZedInstance(ctx context.Context, agent *types.DesktopAgent) (*types.DesktopAgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartZedInstance", ctx, agent)
	ret0, _ := ret[0].(*types.DesktopAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartZedInstance indicates an expected call of StartZedInstance.
func (mr *MockExecutorMockRecorder) StartZedInstance(ctx, agent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartZedInstance", reflect.TypeOf((*MockExecutor)(nil).StartZedInstance), ctx, agent)
}

// StopDesktop mocks base method.
func (m *MockExecutor) StopDesktop(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopDesktop", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopDesktop indicates an expected call of StopDesktop.
func (mr *MockExecutorMockRecorder) StopDesktop(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopDesktop", reflect.TypeOf((*MockExecutor)(nil).StopDesktop), ctx, sessionID)
}

// StopZedInstance mocks base method.
func (m *MockExecutor) StopZedInstance(ctx context.Context, instanceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopZedInstance", ctx, instanceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopZedInstance indicates an expected call of StopZedInstance.
func (mr *MockExecutorMockRecorder) StopZedInstance(ctx, instanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopZedInstance", reflect.TypeOf((*MockExecutor)(nil).StopZedInstance), ctx, instanceID)
}
