// Code generated by MockGen. DO NOT EDIT.
// Source: api/pkg/external-agent/wolf_client_interface.go
//
// Generated by this command:
//
//	mockgen -source api/pkg/external-agent/wolf_client_interface.go -destination api/pkg/external-agent/wolf_client_interface_mocks.go -package external_agent
//

// Package external_agent is a generated GoMock package.
package external_agent

import (
	context "context"
	reflect "reflect"

	wolf "github.com/helixml/helix/api/pkg/wolf"
	gomock "go.uber.org/mock/gomock"
)

// MockWolfClientInterface is a mock of WolfClientInterface interface.
type MockWolfClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWolfClientInterfaceMockRecorder
	isgomock struct{}
}

// MockWolfClientInterfaceMockRecorder is the mock recorder for MockWolfClientInterface.
type MockWolfClientInterfaceMockRecorder struct {
	mock *MockWolfClientInterface
}

// NewMockWolfClientInterface creates a new mock instance.
func NewMockWolfClientInterface(ctrl *gomock.Controller) *MockWolfClientInterface {
	mock := &MockWolfClientInterface{ctrl: ctrl}
	mock.recorder = &MockWolfClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWolfClientInterface) EXPECT() *MockWolfClientInterfaceMockRecorder {
	return m.recorder
}

// AddApp mocks base method.
func (m *MockWolfClientInterface) AddApp(ctx context.Context, app *wolf.App) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddApp", ctx, app)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddApp indicates an expected call of AddApp.
func (mr *MockWolfClientInterfaceMockRecorder) AddApp(ctx, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddApp", reflect.TypeOf((*MockWolfClientInterface)(nil).AddApp), ctx, app)
}

// CreateLobby mocks base method.
func (m *MockWolfClientInterface) CreateLobby(ctx context.Context, req *wolf.CreateLobbyRequest) (*wolf.LobbyCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLobby", ctx, req)
	ret0, _ := ret[0].(*wolf.LobbyCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLobby indicates an expected call of CreateLobby.
func (mr *MockWolfClientInterfaceMockRecorder) CreateLobby(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLobby", reflect.TypeOf((*MockWolfClientInterface)(nil).CreateLobby), ctx, req)
}

// CreateSession mocks base method.
func (m *MockWolfClientInterface) CreateSession(ctx context.Context, session *wolf.Session) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockWolfClientInterfaceMockRecorder) CreateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockWolfClientInterface)(nil).CreateSession), ctx, session)
}

// ListApps mocks base method.
func (m *MockWolfClientInterface) ListApps(ctx context.Context) ([]wolf.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApps", ctx)
	ret0, _ := ret[0].([]wolf.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApps indicates an expected call of ListApps.
func (mr *MockWolfClientInterfaceMockRecorder) ListApps(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApps", reflect.TypeOf((*MockWolfClientInterface)(nil).ListApps), ctx)
}

// ListLobbies mocks base method.
func (m *MockWolfClientInterface) ListLobbies(ctx context.Context) ([]wolf.Lobby, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLobbies", ctx)
	ret0, _ := ret[0].([]wolf.Lobby)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLobbies indicates an expected call of ListLobbies.
func (mr *MockWolfClientInterfaceMockRecorder) ListLobbies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLobbies", reflect.TypeOf((*MockWolfClientInterface)(nil).ListLobbies), ctx)
}

// RemoveApp mocks base method.
func (m *MockWolfClientInterface) RemoveApp(ctx context.Context, appID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveApp", ctx, appID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveApp indicates an expected call of RemoveApp.
func (mr *MockWolfClientInterfaceMockRecorder) RemoveApp(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveApp", reflect.TypeOf((*MockWolfClientInterface)(nil).RemoveApp), ctx, appID)
}

// StopLobby mocks base method.
func (m *MockWolfClientInterface) StopLobby(ctx context.Context, req *wolf.StopLobbyRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopLobby", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopLobby indicates an expected call of StopLobby.
func (mr *MockWolfClientInterfaceMockRecorder) StopLobby(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopLobby", reflect.TypeOf((*MockWolfClientInterface)(nil).StopLobby), ctx, req)
}

// StopSession mocks base method.
func (m *MockWolfClientInterface) StopSession(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopSession indicates an expected call of StopSession.
func (mr *MockWolfClientInterfaceMockRecorder) StopSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopSession", reflect.TypeOf((*MockWolfClientInterface)(nil).StopSession), ctx, sessionID)
}
