//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIApp) DeepCopyInto(out *AIApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIApp.
func (in *AIApp) DeepCopy() *AIApp {
	if in == nil {
		return nil
	}
	out := new(AIApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIAppList) DeepCopyInto(out *AIAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIAppList.
func (in *AIAppList) DeepCopy() *AIAppList {
	if in == nil {
		return nil
	}
	out := new(AIAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIAppSpec) DeepCopyInto(out *AIAppSpec) {
	*out = *in
	if in.Assistants != nil {
		in, out := &in.Assistants, &out.Assistants
		*out = make([]AssistantConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIAppSpec.
func (in *AIAppSpec) DeepCopy() *AIAppSpec {
	if in == nil {
		return nil
	}
	out := new(AIAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIAppStatus) DeepCopyInto(out *AIAppStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIAppStatus.
func (in *AIAppStatus) DeepCopy() *AIAppStatus {
	if in == nil {
		return nil
	}
	out := new(AIAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssistantAPI) DeepCopyInto(out *AssistantAPI) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Query != nil {
		in, out := &in.Query, &out.Query
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssistantAPI.
func (in *AssistantAPI) DeepCopy() *AssistantAPI {
	if in == nil {
		return nil
	}
	out := new(AssistantAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssistantConfig) DeepCopyInto(out *AssistantConfig) {
	*out = *in
	if in.Knowledge != nil {
		in, out := &in.Knowledge, &out.Knowledge
		*out = make([]AssistantKnowledge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.APIs != nil {
		in, out := &in.APIs, &out.APIs
		*out = make([]AssistantAPI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GPTScripts != nil {
		in, out := &in.GPTScripts, &out.GPTScripts
		*out = make([]AssistantGPTScript, len(*in))
		copy(*out, *in)
	}
	if in.Zapier != nil {
		in, out := &in.Zapier, &out.Zapier
		*out = make([]AssistantZapier, len(*in))
		copy(*out, *in)
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]Tool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tests != nil {
		in, out := &in.Tests, &out.Tests
		*out = make([]AssistantTest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssistantConfig.
func (in *AssistantConfig) DeepCopy() *AssistantConfig {
	if in == nil {
		return nil
	}
	out := new(AssistantConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssistantGPTScript) DeepCopyInto(out *AssistantGPTScript) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssistantGPTScript.
func (in *AssistantGPTScript) DeepCopy() *AssistantGPTScript {
	if in == nil {
		return nil
	}
	out := new(AssistantGPTScript)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssistantKnowledge) DeepCopyInto(out *AssistantKnowledge) {
	*out = *in
	out.RAGSettings = in.RAGSettings
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssistantKnowledge.
func (in *AssistantKnowledge) DeepCopy() *AssistantKnowledge {
	if in == nil {
		return nil
	}
	out := new(AssistantKnowledge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssistantTest) DeepCopyInto(out *AssistantTest) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]TestStep, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssistantTest.
func (in *AssistantTest) DeepCopy() *AssistantTest {
	if in == nil {
		return nil
	}
	out := new(AssistantTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssistantZapier) DeepCopyInto(out *AssistantZapier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssistantZapier.
func (in *AssistantZapier) DeepCopy() *AssistantZapier {
	if in == nil {
		return nil
	}
	out := new(AssistantZapier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilestoreSource) DeepCopyInto(out *FilestoreSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilestoreSource.
func (in *FilestoreSource) DeepCopy() *FilestoreSource {
	if in == nil {
		return nil
	}
	out := new(FilestoreSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeSource) DeepCopyInto(out *KnowledgeSource) {
	*out = *in
	out.Filestore = in.Filestore
	in.Web.DeepCopyInto(&out.Web)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeSource.
func (in *KnowledgeSource) DeepCopy() *KnowledgeSource {
	if in == nil {
		return nil
	}
	out := new(KnowledgeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RAGSettings) DeepCopyInto(out *RAGSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RAGSettings.
func (in *RAGSettings) DeepCopy() *RAGSettings {
	if in == nil {
		return nil
	}
	out := new(RAGSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestStep) DeepCopyInto(out *TestStep) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestStep.
func (in *TestStep) DeepCopy() *TestStep {
	if in == nil {
		return nil
	}
	out := new(TestStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tool) DeepCopyInto(out *Tool) {
	*out = *in
	in.Created.DeepCopyInto(&out.Created)
	in.Updated.DeepCopyInto(&out.Updated)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tool.
func (in *Tool) DeepCopy() *Tool {
	if in == nil {
		return nil
	}
	out := new(Tool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolAPIAction) DeepCopyInto(out *ToolAPIAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolAPIAction.
func (in *ToolAPIAction) DeepCopy() *ToolAPIAction {
	if in == nil {
		return nil
	}
	out := new(ToolAPIAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolAPIConfig) DeepCopyInto(out *ToolAPIConfig) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]ToolAPIAction, len(*in))
		copy(*out, *in)
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Query != nil {
		in, out := &in.Query, &out.Query
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolAPIConfig.
func (in *ToolAPIConfig) DeepCopy() *ToolAPIConfig {
	if in == nil {
		return nil
	}
	out := new(ToolAPIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolConfig) DeepCopyInto(out *ToolConfig) {
	*out = *in
	if in.API != nil {
		in, out := &in.API, &out.API
		*out = new(ToolAPIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GPTScript != nil {
		in, out := &in.GPTScript, &out.GPTScript
		*out = new(ToolGPTScriptConfig)
		**out = **in
	}
	if in.Zapier != nil {
		in, out := &in.Zapier, &out.Zapier
		*out = new(ToolZapierConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolConfig.
func (in *ToolConfig) DeepCopy() *ToolConfig {
	if in == nil {
		return nil
	}
	out := new(ToolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolGPTScriptConfig) DeepCopyInto(out *ToolGPTScriptConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolGPTScriptConfig.
func (in *ToolGPTScriptConfig) DeepCopy() *ToolGPTScriptConfig {
	if in == nil {
		return nil
	}
	out := new(ToolGPTScriptConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolZapierConfig) DeepCopyInto(out *ToolZapierConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolZapierConfig.
func (in *ToolZapierConfig) DeepCopy() *ToolZapierConfig {
	if in == nil {
		return nil
	}
	out := new(ToolZapierConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebCrawlerConfig) DeepCopyInto(out *WebCrawlerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebCrawlerConfig.
func (in *WebCrawlerConfig) DeepCopy() *WebCrawlerConfig {
	if in == nil {
		return nil
	}
	out := new(WebCrawlerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebSource) DeepCopyInto(out *WebSource) {
	*out = *in
	if in.URLs != nil {
		in, out := &in.URLs, &out.URLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Crawler = in.Crawler
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebSource.
func (in *WebSource) DeepCopy() *WebSource {
	if in == nil {
		return nil
	}
	out := new(WebSource)
	in.DeepCopyInto(out)
	return out
}
