{{- if .Values.chrome.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helix-controlplane.fullname" . }}-chrome
  labels:
    {{- include "helix-controlplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: chrome
spec:
  type: ClusterIP
  ports:
    - port: 7317
      targetPort: 7317
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: chrome
    {{- include "helix-controlplane.selectorLabels" . | nindent 4 }}
{{- end }}