apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helix-controlplane.fullname" . }}-config
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
data:
  {{- with .Values.envVariables }}
  {{- toYaml . | nindent 4 }}
  {{- end }}