{{- if .Values.haystack.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helix-controlplane.fullname" . }}-haystack
  labels:
    {{- include "helix-controlplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: haystack
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: haystack
    {{- include "helix-controlplane.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helix-controlplane.fullname" . }}-haystack
  labels:
    app.kubernetes.io/component: haystack
    {{- include "helix-controlplane.labels" . | nindent 4 }}
spec:
  {{- if .Values.haystack.pgvector.enabled }}
  # When using bundled pgvector, we must use 1 replica because pgvector is not stateless
  replicas: 1
  {{- else }}
  replicas: {{ .Values.haystack.replicas | default 1 }}
  {{- end }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: haystack
      {{- include "helix-controlplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: haystack
        {{- include "helix-controlplane.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helix-controlplane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: haystack
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.haystack.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.haystack.pgvector.host | default "localhost" }}
            - name: POSTGRES_DATABASE
              value: {{ .Values.haystack.pgvector.database | default "postgres" }}
            - name: POSTGRES_USER
              value: {{ .Values.haystack.pgvector.user | default "postgres" }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.haystack.pgvector.password | default "pgvector" }}
        {{- if .Values.haystack.pgvector.enabled }}
        - name: pgvector
          image: pgvector/pgvector:pg17
          ports:
            - name: tcp-pgvector
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: pgvector
          {{- if .Values.haystack.persistence.enabled }} 
          volumeMounts:
            - name: haystack-storage
              mountPath: /var/lib/postgresql/data
          {{- end }}
        {{- end }}
      {{- if .Values.haystack.persistence.enabled }} 
      volumes:
      - name: haystack-storage
        persistentVolumeClaim:
          claimName: {{ include "helix-controlplane.fullname" . }}-haystack-pvc
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
