apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helix-controlplane.fullname" . }}
  labels:
    app.kubernetes.io/component: controlplane
    {{- include "helix-controlplane.labels" . | nindent 4 }}
spec:
  # Helix can't run multi-node yet, do not set
  # to more than 1 replicas for controlplane
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: controlplane
      {{- include "helix-controlplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: controlplane
        {{- include "helix-controlplane.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helix-controlplane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: controlplane
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "helix-controlplane.fullname" . }}-config
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_URL
              value: {{ .Values.global.serverUrl }}
            - name: FILESTORE_LOCALFS_PATH
              value: {{- with .Values.controlplane }} {{ .filestorePath | default "/filestore" }} {{- else }} "/filestore" {{- end }} 
            - name: TEXT_EXTRACTION_URL
              value: http://{{ include "helix-controlplane.fullname" . }}-llamaindex:5000/api/v1/extract
            - name: RAG_INDEX_URL
              value: http://{{ include "helix-controlplane.fullname" . }}-llamaindex:5000/api/v1/rag/chunk
            - name: RAG_QUERY_URL
              value: http://{{ include "helix-controlplane.fullname" . }}-llamaindex:5000/api/v1/rag/query
            - name: RAG_TYPESENSE_URL
              value: http://{{ include "helix-controlplane.fullname" . }}-typesense:8108
            - name: RAG_TYPESENSE_API_KEY
              value: {{ .Values.typesense.apiKey }}
            - name: TEXT_EXTRACTION_TIKA_URL
              value: http://{{ include "helix-controlplane.fullname" . }}-tika:9998/tika 
            - name: RAG_CRAWLER_LAUNCHER_URL
              value: http://{{ include "helix-controlplane.fullname" . }}-chrome:7317
              {{- with .Values.controlplane.extraEnv }}
              {{- toYaml . | nindent 12 }}
              {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.controlplane.extraVolumeMounts }}
          {{- toYaml .Values.controlplane.extraVolumeMounts | nindent 12 }}
          {{- end }}

          {{- if .Values.persistence.enabled }}
            - name: controlplane-storage
              mountPath: /filestore
          {{- end }}  
        {{- if .Values.controlplane.sidecar }}
        - name: {{ .Values.controlplane.sidecar.name | default "sidecar" }}
          image: "{{ .Values.controlplane.sidecar.image }}"
          imagePullPolicy: "{{ .Values.controlplane.sidecar.imagePullPolicy | default .Values.image.pullPolicy }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.controlplane.sidecar.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.controlplane.sidecar.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.controlplane.sidecar.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.controlplane.sidecar.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end}}
          {{- with .Values.controlplane.sidecar.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end}}
        {{- end }}
      volumes:
      {{- if .Values.controlplane.extraVolumes }}
      {{- toYaml .Values.controlplane.extraVolumes | nindent 6 }}
      {{- end }}

      {{- if .Values.persistence.enabled }}     
      - name: controlplane-storage
        persistentVolumeClaim:
          claimName: {{ include "helix-controlplane.fullname" . }}-controlplane-pvc      
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
