apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helix-controlplane.fullname" . }}
  labels:
    app.kubernetes.io/component: controlplane
    {{- include "helix-controlplane.labels" . | nindent 4 }}
spec:
  # Helix can't run multi-node yet, do not set
  # to more than 1 replicas for controlplane
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: controlplane
      {{- include "helix-controlplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: controlplane
        {{- include "helix-controlplane.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helix-controlplane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: controlplane
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8844
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "helix-controlplane.fullname" . }}-config
          env:
            - name: SERVER_PORT
              value: "8844"
            - name: SERVER_URL
              value: {{ .Values.global.serverUrl }}
            - name: FILESTORE_LOCALFS_PATH
              value: /filestore
            - name: TEXT_EXTRACTION_URL
              value: http://{{ include "helix-controlplane.fullname" . }}-llamaindex:5000/api/v1/extract
            - name: RAG_INDEX_URL
              value: http://{{ include "helix-controlplane.fullname" . }}-llamaindex:5000/api/v1/rag/chunk
            - name: RAG_QUERY_URL
              value: http://{{ include "helix-controlplane.fullname" .
              }}-llamaindex:5000/api/v1/rag/query
            - name: RAG_TYPESENSE_URL
              value: http://{{ include "helix-controlplane.fullname" . }}-typesense:8108
            - name: RAG_TYPESENSE_API_KEY
              value: {{ .Values.typesense.apiKey }}
            - name: TEXT_EXTRACTION_TIKA_URL
              value: http://{{ include "helix-controlplane.fullname" . }}-tika:9998/tika 
            - name: RAG_CRAWLER_CHROME_URL
              value: http://{{ include "helix-controlplane.fullname" . }}-chrome:9222
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: controlplane-storage
              mountPath: /filestore
          {{- end }}       

      {{- if .Values.persistence.enabled }}     
      volumes:
      - name: controlplane-storage
        persistentVolumeClaim:
          claimName: {{ include "helix-controlplane.fullname" . }}-controlplane-pvc      
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
