{{- if and (not .Values.controlplane.runnerToken) (not .Values.controlplane.runnerTokenExistingSecret) }}
{{- $secretName := printf "%s-runner-token" (include "helix-controlplane.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "helix-controlplane.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ if $existingSecret }}{{ index $existingSecret.data "token" }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
{{- end }}
