{{- if .Values.tika.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helix-controlplane.fullname" . }}-tika
  labels:
    {{- include "helix-controlplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: tika
spec:
  type: ClusterIP
  ports:
    - port: 9998
      targetPort: 9998
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: tika
    {{- include "helix-controlplane.selectorLabels" . | nindent 4 }}
{{- end }}