config_version = 5
hostname = 'Helix'
uuid = '5a3f1809-8854-4e7a-8646-07fab869745a'

[api]
socket_path = '/var/run/wolf/wolf.sock'

[gstreamer.audio]
default_audio_params = 'queue max-size-buffers=3 leaky=downstream ! audiorate ! audioconvert'
default_opus_encoder = 'opusenc bitrate={bitrate} bitrate-type=cbr frame-size={packet_duration} bandwidth=fullband audio-type=restricted-lowdelay max-payload-size=1400'
default_sink = '''rtpmoonlightpay_audio name=moonlight_pay packet_duration={packet_duration} encrypt={encrypt} aes_key="{aes_key}" aes_iv="{aes_iv}" !
appsink name=wolf_udp_sink'''
default_source = 'interpipesrc listen-to={session_id}_audio is-live=true stream-sync=restart-ts max-bytes=0 max-buffers=3 block=false'

[gstreamer.video]
default_sink = '''rtpmoonlightpay_video name=moonlight_pay payload_size={payload_size} fec_percentage={fec_percentage} min_required_fec_packets={min_required_fec_packets} !
appsink sync=false name=wolf_udp_sink
'''
default_source = 'interpipesrc listen-to={session_id}_video is-live=true stream-sync=restart-ts max-bytes=0 max-buffers=1 leaky-type=downstream'

    [gstreamer.video.defaults.nvcodec]
    video_params = '''cudaupload !
cudaconvertscale !
video/x-raw(memory:CUDAMemory), width={width}, height={height}, chroma-site={color_range}, format=NV12, colorimetry={color_space}, pixel-aspect-ratio=1/1'''
    video_params_zero_copy = '''glupload !
glcolorconvert !
video/x-raw(memory:GLMemory),format=NV12, width={width}, height={height}, chroma-site={color_range}, colorimetry={color_space}, pixel-aspect-ratio=1/1'''

    [gstreamer.video.defaults.qsv]
    video_params = '''videoconvertscale !
video/x-raw, chroma-site={color_range}, width={width}, height={height}, format=NV12,
colorimetry={color_space}, pixel-aspect-ratio=1/1'''
    video_params_zero_copy = '''vapostproc !
video/x-raw(memory:VAMemory),format=NV12, chroma-site={color_range},
colorimetry={color_space}, pixel-aspect-ratio=1/1'''

    [gstreamer.video.defaults.va]
    video_params = '''vapostproc !
video/x-raw, chroma-site={color_range}, width={width}, height={height}, format=NV12,
colorimetry={color_space}, pixel-aspect-ratio=1/1'''
    video_params_zero_copy = '''vapostproc !
video/x-raw(memory:VAMemory), format=NV12, chroma-site={color_range}, width={width}, height={height},
colorimetry={color_space}, pixel-aspect-ratio=1/1'''

    [[gstreamer.video.av1_encoders]]
    check_elements = [ 'nvav1enc', 'cudaconvertscale', 'cudaupload' ]
    encoder_pipeline = '''nvav1enc gop-size=-1 bitrate={bitrate} rc-mode=cbr zerolatency=true preset=p1 tune=ultra-low-latency multi-pass=two-pass-quarter !
av1parse !
video/x-av1, stream-format=obu-stream, alignment=frame, profile=main'''
    plugin_name = 'nvcodec'

    [[gstreamer.video.av1_encoders]]
    check_elements = [ 'qsvav1enc', 'vapostproc' ]
    encoder_pipeline = '''qsvav1enc gop-size=0 ref-frames=1 bitrate={bitrate} rate-control=cbr low-latency=1 target-usage=6 !
av1parse !
video/x-av1, stream-format=obu-stream, alignment=frame, profile=main'''
    plugin_name = 'qsv'

    [[gstreamer.video.av1_encoders]]
    check_elements = [ 'vaav1enc', 'vapostproc' ]
    encoder_pipeline = '''vaav1enc ref-frames=1 bitrate={bitrate} cpb-size={bitrate} key-int-max=1024 rate-control=cqp target-usage=6 !
av1parse !
video/x-av1, stream-format=obu-stream, alignment=frame, profile=main'''
    plugin_name = 'va'

    [[gstreamer.video.av1_encoders]]
    check_elements = [ 'vaav1lpenc', 'vapostproc' ]
    encoder_pipeline = '''vaav1lpenc ref-frames=1 bitrate={bitrate} cpb-size={bitrate} key-int-max=1024 rate-control=cqp target-usage=6 !
av1parse !
video/x-av1, stream-format=obu-stream, alignment=frame, profile=main'''
    plugin_name = 'va'

    [[gstreamer.video.av1_encoders]]
    check_elements = [ 'av1enc' ]
    encoder_pipeline = '''av1enc usage-profile=realtime end-usage=vbr target-bitrate={bitrate} !
av1parse !
video/x-av1, stream-format=obu-stream, alignment=frame, profile=main'''
    plugin_name = 'aom'
    video_params = '''videoconvertscale !
videorate !
video/x-raw, width={width}, height={height}, framerate={fps}/1, format=I420,
chroma-site={color_range}, colorimetry={color_space}'''
    video_params_zero_copy = '''videoconvertscale !
videorate !
video/x-raw, width={width}, height={height}, framerate={fps}/1, format=I420,
chroma-site={color_range}, colorimetry={color_space}'''

    [[gstreamer.video.h264_encoders]]
    check_elements = [ 'nvh264enc', 'cudaconvertscale', 'cudaupload' ]
    encoder_pipeline = '''nvh264enc preset=low-latency-hq zerolatency=true gop-size=0 rc-mode=cbr-ld-hq bitrate={bitrate} aud=false !
h264parse !
video/x-h264, profile=main, stream-format=byte-stream'''
    plugin_name = 'nvcodec'

    [[gstreamer.video.h264_encoders]]
    check_elements = [ 'qsvh264enc', 'vapostproc' ]
    encoder_pipeline = '''qsvh264enc b-frames=0 gop-size=0 idr-interval=1 ref-frames=1 bitrate={bitrate} rate-control=cbr target-usage=6  !
h264parse !
video/x-h264, profile=main, stream-format=byte-stream'''
    plugin_name = 'qsv'

    [[gstreamer.video.h264_encoders]]
    check_elements = [ 'vah264enc', 'vapostproc' ]
    encoder_pipeline = '''vah264enc aud=false b-frames=0 ref-frames=1 num-slices={slices_per_frame} bitrate={bitrate} cpb-size={bitrate} key-int-max=1024 rate-control=cqp target-usage=6 !
h264parse !
video/x-h264, profile=main, stream-format=byte-stream'''
    plugin_name = 'va'

    [[gstreamer.video.h264_encoders]]
    check_elements = [ 'vah264lpenc', 'vapostproc' ]
    encoder_pipeline = '''vah264lpenc aud=false b-frames=0 ref-frames=1 num-slices={slices_per_frame} bitrate={bitrate} cpb-size={bitrate} key-int-max=1024 rate-control=cqp target-usage=6 !
h264parse !
video/x-h264, profile=main, stream-format=byte-stream'''
    plugin_name = 'va'

    [[gstreamer.video.h264_encoders]]
    check_elements = [ 'x264enc' ]
    encoder_pipeline = '''x264enc pass=qual tune=zerolatency speed-preset=superfast b-adapt=false bframes=0 ref=1
sliced-threads=true threads={slices_per_frame} option-string="slices={slices_per_frame}:keyint=infinite:open-gop=0"
b-adapt=false bitrate={bitrate} aud=false !
video/x-h264, profile=high, stream-format=byte-stream'''
    plugin_name = 'x264'

    [[gstreamer.video.hevc_encoders]]
    check_elements = [ 'nvh265enc', 'cudaconvertscale', 'cudaupload' ]
    encoder_pipeline = '''nvh265enc gop-size=-1 bitrate={bitrate} aud=false rc-mode=cbr zerolatency=true preset=p1 tune=ultra-low-latency multi-pass=two-pass-quarter !
h265parse !
video/x-h265, profile=main, stream-format=byte-stream'''
    plugin_name = 'nvcodec'

    [[gstreamer.video.hevc_encoders]]
    check_elements = [ 'qsvh265enc', 'vapostproc' ]
    encoder_pipeline = '''qsvh265enc b-frames=0 gop-size=0 idr-interval=1 ref-frames=1 bitrate={bitrate} rate-control=cbr low-latency=1 target-usage=6 !
h265parse !
video/x-h265, profile=main, stream-format=byte-stream'''
    plugin_name = 'qsv'

    [[gstreamer.video.hevc_encoders]]
    check_elements = [ 'vah265enc', 'vapostproc' ]
    encoder_pipeline = '''vah265enc aud=false b-frames=0 ref-frames=1 num-slices={slices_per_frame} bitrate={bitrate} cpb-size={bitrate} key-int-max=1024 rate-control=cqp target-usage=6 !
h265parse !
video/x-h265, profile=main, stream-format=byte-stream'''
    plugin_name = 'va'

    [[gstreamer.video.hevc_encoders]]
    check_elements = [ 'vah265lpenc', 'vapostproc' ]
    encoder_pipeline = '''vah265lpenc aud=false b-frames=0 ref-frames=1 num-slices={slices_per_frame} bitrate={bitrate} cpb-size={bitrate} key-int-max=1024 rate-control=cqp target-usage=6 !
h265parse !
video/x-h265, profile=main, stream-format=byte-stream'''
    plugin_name = 'va'

    [[gstreamer.video.hevc_encoders]]
    check_elements = [ 'x265enc' ]
    encoder_pipeline = '''x265enc tune=zerolatency speed-preset=superfast bitrate={bitrate}
option-string="info=0:keyint=-1:qp=28:repeat-headers=1:slices={slices_per_frame}:aud=0:annexb=1:log-level=3:open-gop=0:bframes=0:intra-refresh=0" !
video/x-h265, profile=main, stream-format=byte-stream'''
    plugin_name = 'x265'
    video_params = '''videoconvertscale !
videorate !
video/x-raw, width={width}, height={height}, framerate={fps}/1, format=I420,
chroma-site={color_range}, colorimetry={color_space}'''
    video_params_zero_copy = '''videoconvertscale !
videorate !
video/x-raw, width={width}, height={height}, framerate={fps}/1, format=I420,
chroma-site={color_range}, colorimetry={color_space}'''

[[apps]]
icon_png_path = 'https://games-on-whales.github.io/wildlife/apps/xfce/assets/icon.png'
title = 'Desktop (xfce)'

    [apps.runner]
    base_create_json = '''{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": false,
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
'''
    devices = []
    env = [ 'GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*' ]
    image = 'ghcr.io/games-on-whales/xfce:edge'
    mounts = []
    name = 'WolfXFCE'
    ports = []
    type = 'docker'

[[apps]]
start_audio_server = false
start_virtual_compositor = false
title = 'Test ball'

    [apps.audio]
    source = 'audiotestsrc wave=ticks is-live=true'

    [apps.runner]
    run_cmd = "sh -c \"while :; do echo 'running...'; sleep 10; done\""
    type = 'process'

    [apps.video]
    source = '''videotestsrc pattern=ball flip=true is-live=true !
video/x-raw, framerate={fps}/1
'''

[[paired_clients]]
app_state_folder = '342532221405053742'
client_cert = '''-----BEGIN CERTIFICATE-----
MIICvzCCAaegAwIBAgIBADANBgkqhkiG9w0BAQsFADAjMSEwHwYDVQQDDBhOVklE
SUEgR2FtZVN0cmVhbSBDbGllbnQwHhcNMjUwOTA5MTMzMzExWhcNNDUwOTA0MTMz
MzExWjAjMSEwHwYDVQQDDBhOVklESUEgR2FtZVN0cmVhbSBDbGllbnQwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC2AI5H3f3Dq/ngGPhnLWT2NiUtqgMZ
MDLrJC3dAnezndYsJOqxEe5U5pjsU6L3xSvjNwevs1yNCIM7YeT6yoLLZ5GADwCW
SV+VOMWPdgZYMup6qTXhZ+8PFgJ1IwnzNulJOIMbCzr3pvJpkLFsBa/RZCCaHVci
iJwjQhADl+/EJrPqR1J71ftkY/w921c90kO/qrdavSgZeXQV9JhT04jfXq79oaSK
bYaXowfQoByAy0zGBPWuYZbMEFDaby6iEPpSsafBCPoDBVlhku2/DmXg1G3UJUN4
0/NlQZA5MAURn78nJWZjknTNgiIm99qqKaT8mK3yQ9JI1J6RA2/XkJ57AgMBAAEw
DQYJKoZIhvcNAQELBQADggEBAGVw+RQy5YLV6xU6ZekBySOqQuJDs3qlu+D3i/Kz
rp3sS6jVsQOCXhmGvB7UGTzaHsQXdwk42Zn6pHtuY2YAonsuIQvbjYE0bq0+ECrE
y4SE4EWRNE2P44PSLMx0QRU4pR9Kgc8x8FULKOuhGy9U05w2rrIGQFo8G74ui8bu
i/2hR1epcaIhtVqzls2Tar/jAi7syZeAJT54RW5zewcoLqGj7tkc47Mg6r0B+DVg
/sfFFwD+G1mIQwN6BGp+TiBNbnKdPfHtW8QTPUki04kIhioBWWPKA3GFdY23T5qv
r8OEdVzBvXgDs5tieIynLdse1PjzlfE2BiKPaKfZBWwuuq0=
-----END CERTIFICATE-----
'''

    [paired_clients.settings]
    controllers_override = []
    h_scroll_acceleration = 1.0
    mouse_acceleration = 1.0
    run_gid = 1000
    run_uid = 1000
    v_scroll_acceleration = 1.0

[[paired_clients]]
app_state_folder = '342532221405053742'
client_cert = '''-----BEGIN CERTIFICATE-----
MIICvzCCAaegAwIBAgIBADANBgkqhkiG9w0BAQsFADAjMSEwHwYDVQQDDBhOVklE
SUEgR2FtZVN0cmVhbSBDbGllbnQwHhcNMjUwOTA5MTMzMzExWhcNNDUwOTA0MTMz
MzExWjAjMSEwHwYDVQQDDBhOVklESUEgR2FtZVN0cmVhbSBDbGllbnQwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC2AI5H3f3Dq/ngGPhnLWT2NiUtqgMZ
MDLrJC3dAnezndYsJOqxEe5U5pjsU6L3xSvjNwevs1yNCIM7YeT6yoLLZ5GADwCW
SV+VOMWPdgZYMup6qTXhZ+8PFgJ1IwnzNulJOIMbCzr3pvJpkLFsBa/RZCCaHVci
iJwjQhADl+/EJrPqR1J71ftkY/w921c90kO/qrdavSgZeXQV9JhT04jfXq79oaSK
bYaXowfQoByAy0zGBPWuYZbMEFDaby6iEPpSsafBCPoDBVlhku2/DmXg1G3UJUN4
0/NlQZA5MAURn78nJWZjknTNgiIm99qqKaT8mK3yQ9JI1J6RA2/XkJ57AgMBAAEw
DQYJKoZIhvcNAQELBQADggEBAGVw+RQy5YLV6xU6ZekBySOqQuJDs3qlu+D3i/Kz
rp3sS6jVsQOCXhmGvB7UGTzaHsQXdwk42Zn6pHtuY2YAonsuIQvbjYE0bq0+ECrE
y4SE4EWRNE2P44PSLMx0QRU4pR9Kgc8x8FULKOuhGy9U05w2rrIGQFo8G74ui8bu
i/2hR1epcaIhtVqzls2Tar/jAi7syZeAJT54RW5zewcoLqGj7tkc47Mg6r0B+DVg
/sfFFwD+G1mIQwN6BGp+TiBNbnKdPfHtW8QTPUki04kIhioBWWPKA3GFdY23T5qv
r8OEdVzBvXgDs5tieIynLdse1PjzlfE2BiKPaKfZBWwuuq0=
-----END CERTIFICATE-----
'''

    [paired_clients.settings]
    controllers_override = []
    h_scroll_acceleration = 1.0
    mouse_acceleration = 1.0
    run_gid = 1000
    run_uid = 1000
    v_scroll_acceleration = 1.0

[[paired_clients]]
app_state_folder = '342532221405053742'
client_cert = '''-----BEGIN CERTIFICATE-----
MIICvzCCAaegAwIBAgIBADANBgkqhkiG9w0BAQsFADAjMSEwHwYDVQQDDBhOVklE
SUEgR2FtZVN0cmVhbSBDbGllbnQwHhcNMjUwOTA5MTMzMzExWhcNNDUwOTA0MTMz
MzExWjAjMSEwHwYDVQQDDBhOVklESUEgR2FtZVN0cmVhbSBDbGllbnQwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC2AI5H3f3Dq/ngGPhnLWT2NiUtqgMZ
MDLrJC3dAnezndYsJOqxEe5U5pjsU6L3xSvjNwevs1yNCIM7YeT6yoLLZ5GADwCW
SV+VOMWPdgZYMup6qTXhZ+8PFgJ1IwnzNulJOIMbCzr3pvJpkLFsBa/RZCCaHVci
iJwjQhADl+/EJrPqR1J71ftkY/w921c90kO/qrdavSgZeXQV9JhT04jfXq79oaSK
bYaXowfQoByAy0zGBPWuYZbMEFDaby6iEPpSsafBCPoDBVlhku2/DmXg1G3UJUN4
0/NlQZA5MAURn78nJWZjknTNgiIm99qqKaT8mK3yQ9JI1J6RA2/XkJ57AgMBAAEw
DQYJKoZIhvcNAQELBQADggEBAGVw+RQy5YLV6xU6ZekBySOqQuJDs3qlu+D3i/Kz
rp3sS6jVsQOCXhmGvB7UGTzaHsQXdwk42Zn6pHtuY2YAonsuIQvbjYE0bq0+ECrE
y4SE4EWRNE2P44PSLMx0QRU4pR9Kgc8x8FULKOuhGy9U05w2rrIGQFo8G74ui8bu
i/2hR1epcaIhtVqzls2Tar/jAi7syZeAJT54RW5zewcoLqGj7tkc47Mg6r0B+DVg
/sfFFwD+G1mIQwN6BGp+TiBNbnKdPfHtW8QTPUki04kIhioBWWPKA3GFdY23T5qv
r8OEdVzBvXgDs5tieIynLdse1PjzlfE2BiKPaKfZBWwuuq0=
-----END CERTIFICATE-----
'''

    [paired_clients.settings]
    controllers_override = []
    h_scroll_acceleration = 1.0
    mouse_acceleration = 1.0
    run_gid = 1000
    run_uid = 1000
    v_scroll_acceleration = 1.0

[[paired_clients]]
app_state_folder = '6061047231751940182'
client_cert = '''-----BEGIN CERTIFICATE-----
MIICvzCCAaegAwIBAgIBADANBgkqhkiG9w0BAQsFADAjMSEwHwYDVQQDDBhOVklE
SUEgR2FtZVN0cmVhbSBDbGllbnQwHhcNMjUwOTI1MTY1NjM0WhcNNDUwOTIwMTY1
NjM0WjAjMSEwHwYDVQQDDBhOVklESUEgR2FtZVN0cmVhbSBDbGllbnQwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDKeZgPl/EM0Q3+6eJQ3y7LbQIyiWu/
8oYvCN2Kn96ikNCBC/8sJJ0pFwYnoiVmeHO2Ay8wj93AOo8KDKI8iFMnnyfB+U0D
dDuMcdbEMcC2Zy2AhnkVtwLkwZ4HS2fs08DzjYiEE/dDqGUwakjW+EyKTmIkcfpn
keUwlFcXjMcEwZbmSEAJ+ZAAy6zkl2G36RkO0/ddTB/XJLoAQJqMbmMRRde2Cbyx
niBCWI8yYkddPtWN64cT+oVwvYOZhtoUXXoM5STjVl8bCNJfM/Agz3C5HKNcOegI
VppDnyqhXR9QlxaJ2kGsdoQTbKj4Mq7UOlm0C8S3KoZQl+JjQGjKyoKDAgMBAAEw
DQYJKoZIhvcNAQELBQADggEBABZyX0RB2YOgROh2/GLMw/3AOKE++2v0R3/nRjjS
iatxIpec7W6/PE0ZXHC9jsImZRiZEi1uYOO9jfARiBw1YJMBKNGftB61ycPQ0xRa
oMz1VkwvuuFZtSLXHNv+EIny9B7CzMApeLofF2VrJo4xXWZttD+fOFDQVN7UWoJE
xai5kCwE2kwljvEnz4U1XqjzDd/eZG5x1jEZMZws7Jr3ilD0lKthd30VdPhS5440
klWnke8TrbhY5eIOjKMGf4aRdR4FStR33hlJesBBIWj0pKqqUdMhyr6Of+0EpZR0
88JFtMEX+y2mMg2JVxzXIp7HquJF1z7hqHQo4/sb5O6At04=
-----END CERTIFICATE-----
'''

    [paired_clients.settings]
    controllers_override = []
    h_scroll_acceleration = 1.0
    mouse_acceleration = 1.0
    run_gid = 1000
    run_uid = 1000
    v_scroll_acceleration = 1.0

[[paired_clients]]
app_state_folder = '342532221405053742'
client_cert = '''-----BEGIN CERTIFICATE-----
MIICvzCCAaegAwIBAgIBADANBgkqhkiG9w0BAQsFADAjMSEwHwYDVQQDDBhOVklE
SUEgR2FtZVN0cmVhbSBDbGllbnQwHhcNMjUwOTA5MTMzMzExWhcNNDUwOTA0MTMz
MzExWjAjMSEwHwYDVQQDDBhOVklESUEgR2FtZVN0cmVhbSBDbGllbnQwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC2AI5H3f3Dq/ngGPhnLWT2NiUtqgMZ
MDLrJC3dAnezndYsJOqxEe5U5pjsU6L3xSvjNwevs1yNCIM7YeT6yoLLZ5GADwCW
SV+VOMWPdgZYMup6qTXhZ+8PFgJ1IwnzNulJOIMbCzr3pvJpkLFsBa/RZCCaHVci
iJwjQhADl+/EJrPqR1J71ftkY/w921c90kO/qrdavSgZeXQV9JhT04jfXq79oaSK
bYaXowfQoByAy0zGBPWuYZbMEFDaby6iEPpSsafBCPoDBVlhku2/DmXg1G3UJUN4
0/NlQZA5MAURn78nJWZjknTNgiIm99qqKaT8mK3yQ9JI1J6RA2/XkJ57AgMBAAEw
DQYJKoZIhvcNAQELBQADggEBAGVw+RQy5YLV6xU6ZekBySOqQuJDs3qlu+D3i/Kz
rp3sS6jVsQOCXhmGvB7UGTzaHsQXdwk42Zn6pHtuY2YAonsuIQvbjYE0bq0+ECrE
y4SE4EWRNE2P44PSLMx0QRU4pR9Kgc8x8FULKOuhGy9U05w2rrIGQFo8G74ui8bu
i/2hR1epcaIhtVqzls2Tar/jAi7syZeAJT54RW5zewcoLqGj7tkc47Mg6r0B+DVg
/sfFFwD+G1mIQwN6BGp+TiBNbnKdPfHtW8QTPUki04kIhioBWWPKA3GFdY23T5qv
r8OEdVzBvXgDs5tieIynLdse1PjzlfE2BiKPaKfZBWwuuq0=
-----END CERTIFICATE-----
'''

    [paired_clients.settings]
    controllers_override = []
    h_scroll_acceleration = 1.0
    mouse_acceleration = 1.0
    run_gid = 1000
    run_uid = 1000
    v_scroll_acceleration = 1.0

[[paired_clients]]
app_state_folder = '342532221405053742'
client_cert = '''-----BEGIN CERTIFICATE-----
MIICvzCCAaegAwIBAgIBADANBgkqhkiG9w0BAQsFADAjMSEwHwYDVQQDDBhOVklE
SUEgR2FtZVN0cmVhbSBDbGllbnQwHhcNMjUwOTA5MTMzMzExWhcNNDUwOTA0MTMz
MzExWjAjMSEwHwYDVQQDDBhOVklESUEgR2FtZVN0cmVhbSBDbGllbnQwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC2AI5H3f3Dq/ngGPhnLWT2NiUtqgMZ
MDLrJC3dAnezndYsJOqxEe5U5pjsU6L3xSvjNwevs1yNCIM7YeT6yoLLZ5GADwCW
SV+VOMWPdgZYMup6qTXhZ+8PFgJ1IwnzNulJOIMbCzr3pvJpkLFsBa/RZCCaHVci
iJwjQhADl+/EJrPqR1J71ftkY/w921c90kO/qrdavSgZeXQV9JhT04jfXq79oaSK
bYaXowfQoByAy0zGBPWuYZbMEFDaby6iEPpSsafBCPoDBVlhku2/DmXg1G3UJUN4
0/NlQZA5MAURn78nJWZjknTNgiIm99qqKaT8mK3yQ9JI1J6RA2/XkJ57AgMBAAEw
DQYJKoZIhvcNAQELBQADggEBAGVw+RQy5YLV6xU6ZekBySOqQuJDs3qlu+D3i/Kz
rp3sS6jVsQOCXhmGvB7UGTzaHsQXdwk42Zn6pHtuY2YAonsuIQvbjYE0bq0+ECrE
y4SE4EWRNE2P44PSLMx0QRU4pR9Kgc8x8FULKOuhGy9U05w2rrIGQFo8G74ui8bu
i/2hR1epcaIhtVqzls2Tar/jAi7syZeAJT54RW5zewcoLqGj7tkc47Mg6r0B+DVg
/sfFFwD+G1mIQwN6BGp+TiBNbnKdPfHtW8QTPUki04kIhioBWWPKA3GFdY23T5qv
r8OEdVzBvXgDs5tieIynLdse1PjzlfE2BiKPaKfZBWwuuq0=
-----END CERTIFICATE-----
'''

    [paired_clients.settings]
    controllers_override = []
    h_scroll_acceleration = 1.0
    mouse_acceleration = 1.0
    run_gid = 1000
    run_uid = 1000
    v_scroll_acceleration = 1.0
