// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -source types.go -destination types_mocks.go -package model
//

// Package model is a generated GoMock package.
package model

import (
	context "context"
	exec "os/exec"
	reflect "reflect"

	types "github.com/helixml/helix/api/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockModel is a mock of Model interface.
type MockModel struct {
	ctrl     *gomock.Controller
	recorder *MockModelMockRecorder
	isgomock struct{}
}

// MockModelMockRecorder is the mock recorder for MockModel.
type MockModelMockRecorder struct {
	mock *MockModel
}

// NewMockModel creates a new mock instance.
func NewMockModel(ctrl *gomock.Controller) *MockModel {
	mock := &MockModel{ctrl: ctrl}
	mock.recorder = &MockModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModel) EXPECT() *MockModelMockRecorder {
	return m.recorder
}

// GetCommand mocks base method.
func (m *MockModel) GetCommand(ctx context.Context, sessionFilter types.SessionFilter, config types.RunnerProcessConfig) (*exec.Cmd, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommand", ctx, sessionFilter, config)
	ret0, _ := ret[0].(*exec.Cmd)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommand indicates an expected call of GetCommand.
func (mr *MockModelMockRecorder) GetCommand(ctx, sessionFilter, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommand", reflect.TypeOf((*MockModel)(nil).GetCommand), ctx, sessionFilter, config)
}

// GetConcurrency mocks base method.
func (m *MockModel) GetConcurrency() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConcurrency")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetConcurrency indicates an expected call of GetConcurrency.
func (mr *MockModelMockRecorder) GetConcurrency() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConcurrency", reflect.TypeOf((*MockModel)(nil).GetConcurrency))
}

// GetContextLength mocks base method.
func (m *MockModel) GetContextLength() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContextLength")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetContextLength indicates an expected call of GetContextLength.
func (mr *MockModelMockRecorder) GetContextLength() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContextLength", reflect.TypeOf((*MockModel)(nil).GetContextLength))
}

// GetMemoryRequirements mocks base method.
func (m *MockModel) GetMemoryRequirements(mode types.SessionMode) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemoryRequirements", mode)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetMemoryRequirements indicates an expected call of GetMemoryRequirements.
func (mr *MockModelMockRecorder) GetMemoryRequirements(mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemoryRequirements", reflect.TypeOf((*MockModel)(nil).GetMemoryRequirements), mode)
}

// GetTask mocks base method.
func (m *MockModel) GetTask(session *types.Session, fileManager SessionFileManager) (*types.RunnerTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", session, fileManager)
	ret0, _ := ret[0].(*types.RunnerTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockModelMockRecorder) GetTask(session, fileManager any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockModel)(nil).GetTask), session, fileManager)
}

// GetTextStreams mocks base method.
func (m *MockModel) GetTextStreams(mode types.SessionMode, eventHandler WorkerEventHandler) (*TextStream, *TextStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTextStreams", mode, eventHandler)
	ret0, _ := ret[0].(*TextStream)
	ret1, _ := ret[1].(*TextStream)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTextStreams indicates an expected call of GetTextStreams.
func (mr *MockModelMockRecorder) GetTextStreams(mode, eventHandler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTextStreams", reflect.TypeOf((*MockModel)(nil).GetTextStreams), mode, eventHandler)
}

// GetType mocks base method.
func (m *MockModel) GetType() types.SessionType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(types.SessionType)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockModelMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockModel)(nil).GetType))
}

// PrepareFiles mocks base method.
func (m *MockModel) PrepareFiles(session *types.Session, isInitialSession bool, fileManager SessionFileManager) (*types.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareFiles", session, isInitialSession, fileManager)
	ret0, _ := ret[0].(*types.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareFiles indicates an expected call of PrepareFiles.
func (mr *MockModelMockRecorder) PrepareFiles(session, isInitialSession, fileManager any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareFiles", reflect.TypeOf((*MockModel)(nil).PrepareFiles), session, isInitialSession, fileManager)
}

// MockSessionFileManager is a mock of SessionFileManager interface.
type MockSessionFileManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionFileManagerMockRecorder
	isgomock struct{}
}

// MockSessionFileManagerMockRecorder is the mock recorder for MockSessionFileManager.
type MockSessionFileManagerMockRecorder struct {
	mock *MockSessionFileManager
}

// NewMockSessionFileManager creates a new mock instance.
func NewMockSessionFileManager(ctrl *gomock.Controller) *MockSessionFileManager {
	mock := &MockSessionFileManager{ctrl: ctrl}
	mock.recorder = &MockSessionFileManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionFileManager) EXPECT() *MockSessionFileManagerMockRecorder {
	return m.recorder
}

// DownloadFile mocks base method.
func (m *MockSessionFileManager) DownloadFile(remotePath, localPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", remotePath, localPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockSessionFileManagerMockRecorder) DownloadFile(remotePath, localPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockSessionFileManager)(nil).DownloadFile), remotePath, localPath)
}

// DownloadFolder mocks base method.
func (m *MockSessionFileManager) DownloadFolder(remotePath, localPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFolder", remotePath, localPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadFolder indicates an expected call of DownloadFolder.
func (mr *MockSessionFileManagerMockRecorder) DownloadFolder(remotePath, localPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFolder", reflect.TypeOf((*MockSessionFileManager)(nil).DownloadFolder), remotePath, localPath)
}

// GetFolder mocks base method.
func (m *MockSessionFileManager) GetFolder() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFolder")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFolder indicates an expected call of GetFolder.
func (mr *MockSessionFileManagerMockRecorder) GetFolder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFolder", reflect.TypeOf((*MockSessionFileManager)(nil).GetFolder))
}
