# permissions for end users to edit genaiapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: genaiapp-editor-role
rules:
- apiGroups:
  - app.aispec.org
  resources:
  - genaiapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.aispec.org
  resources:
  - genaiapps/status
  verbs:
  - get
