---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - aispec.aispec.org
  resources:
  - aispecs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aispec.aispec.org
  resources:
  - aispecs/finalizers
  verbs:
  - update
- apiGroups:
  - aispec.aispec.org
  resources:
  - aispecs/status
  verbs:
  - get
  - patch
  - update
