id = "html"
name = "HTML"
version = "0.2.2"
schema_version = 1
description = "HTML support."
repository = "https://github.com/zed-industries/zed"
authors = ["Isaac Clayton <slightknack@gmail.com>"]
themes = []
icon_themes = []
languages = ["languages/html"]
capabilities = []

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.html]
repository = "https://github.com/tree-sitter/tree-sitter-html"
rev = "bfa075d83c6b97cd48440b3829ab8d24a2319809"

[language_servers.vscode-html-language-server]
language = "HTML"
languages = []

[language_servers.vscode-html-language-server.language_ids]
HTML = "html"
CSS = "css"

[context_servers]

[slash_commands]

[indexed_docs_providers]
