name: custom-rag-knowledge
description: |
  A simple app that demonstrates how to setup Helix with knowledge from a
  custom RAG server
assistants:
- name: Helix
  description: Knowledge about cars
  knowledge:
  - name: cars
    rag_settings:
      disable_chunking: true # Pass the entire document to the RAG server
      index_url: http://1rvyoove1fvtgxtm3t38yf.webrelay.io/api/index
      query_url: http://1rvyoove1fvtgxtm3t38yf.webrelay.io/api/index/query
      # Optional endpoint such as DELETE /api/index/<data_entity_id> 
      # that Helix will call when the knowledge is deleted to delete the indexed data
      delete_url: http://1rvyoove1fvtgxtm3t38yf.webrelay.io/api/index/
    source:
      web:
        urls:
        # URL contains a simple text file with the following content:
        # 
        # Karolis has a green car
        # Luke has a blue car
        # Kai has a red car
        - https://gist.githubusercontent.com/rusenask/d7d12da5bf8dd11a512e2f8143a4bd84/raw/bbf65a70aad34057b5595cb2aeaa8cf0c7d0277d/cars