apiVersion: app.aispec.org/v1alpha1
kind: AIApp
metadata:
  name: rag-app
spec:
  assistants:
    - name: Default Assistant
      model: microsoft/phi-4
      type: text
      knowledge:
        - name: arxiv
          rag_settings:
            prompt_template: |
              {{- if .RagResults }}
              We have found the following context you may refer to in your answer:
              {{- range .RagResults }}
              <article>
                <document_id>
                  {{ .DocumentID }}
                </document_id>
                <content>
                  {{ .Content }}
                </content>
              </article>
              {{- end }}

              IMPORTANT: When referencing documents, always use EXACTLY the document_id values provided above. DO NOT extract or use page IDs from URLs within the content. Always provide references in the body of your answer in the format '[DOC_ID:DocumentID]'. For example, "The answer is 42 [DOC_ID:f6962c8007]." NOT "[DOC_ID:123456]" where 123456 might be a page ID in a URL.

              Always provide references in the body of your answer!

              After completing your answer, create an excerpt section with important quotes from each referenced document.

              Follow these steps:
              1. Identify each unique document_id you cited in your answer
              2. For each document, select a representative quote (1-2 sentences) that best supports your answer
              3. Include each document exactly once in the excerpt block using the format below

              ⚠️ SYSTEM ERROR PREVENTION NOTICE ⚠️
              ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
              The document database processes each document_id only once. Duplicate entries
              will trigger this error:

              ERROR: Duplicate document_id detected. Excerpt processing failed.
              Document with duplicate entries: [document_id]. Please provide exactly 
              one excerpt per document_id.
              ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

              Required excerpt format:

              ---
              <excerpts>
                <excerpt>
                  <document_id>document-id-you-cited</document_id>
                  <snippet>A representative quote from this document that supports your answer.</snippet>
                </excerpt>
                <excerpt>
                  <document_id>another-document-id-you-cited</document_id>
                  <snippet>A key quote from this document that supports your answer.</snippet>
                </excerpt>
              </excerpts>
              ---

              FINAL CHECK:
              - Each document appears exactly once in your excerpts
              - No introductory text appears before the excerpt block
              - All document_ids match those you cited in your answer

              {{- end }}

              {{- if .KnowledgeResults }}
              We have found the following context you may refer to in your answer:
              {{- range .KnowledgeResults }}
              {{- if .DocumentID }}
              <document_id>
                {{ .DocumentID }}
              </document_id>
              {{- end }}
              <article>
                {{- if .Source }}
                <source>
                  {{ .Source }}
                </source>
                {{- end }}
                {{- if .Description }}
                <description>
                  {{ .Description }}
                </description>
                {{- end }}
                <content>
                  {{ .Content }}
                </content>
              </article>
              {{- end }}

              IMPORTANT: When referencing documents, always use EXACTLY the document_id values provided above. DO NOT extract or use page IDs from URLs within the content. Always provide references in the body of your answer in the format '[DOC_ID:DocumentID]'. For example, "The answer is 42 [DOC_ID:f6962c8007]." NOT "[DOC_ID:123456]" where 123456 might be a page ID in a URL.

              Always provide references in the body of your answer!

              After completing your answer, create an excerpt section with important quotes from each referenced document.

              Follow these steps:
              1. Identify each unique document_id you cited in your answer
              2. For each document, select a representative quote (1-2 sentences) that best supports your answer
              3. Include each document exactly once in the excerpt block using the format below

              ⚠️ SYSTEM ERROR PREVENTION NOTICE ⚠️
              ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
              The document database processes each document_id only once. Duplicate entries
              will trigger this error:

              ERROR: Duplicate document_id detected. Excerpt processing failed.
              Document with duplicate entries: [document_id]. Please provide exactly 
              one excerpt per document_id.
              ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

              Required excerpt format:
              
              <excerpts>
                <excerpt>
                  <document_id>document-id-you-cited</document_id>
                  <snippet>A representative quote from this document that supports your answer.</snippet>
                </excerpt>
                <excerpt>
                  <document_id>another-document-id-you-cited</document_id>
                  <snippet>A key quote from this document that supports your answer.</snippet>
                </excerpt>
              </excerpts>

              FINAL CHECK:
              - No title/header such as "# Excerpts" as this is going to be invisible for the users              
              - Do not mix-up document_id and source, these are two different things and things will break if you do
              - Each document appears exactly once in your excerpts
              - No introductory text appears before the excerpt block
              - All document_ids match those you cited in your answer

              {{- end }}

              Here is the question from the user:
              {{.Question}}
          source:
            filestore:
              path: arxiv
          refresh_enabled: false
