name: helix-docs
image: https://lh3.googleusercontent.com/d/1HaiL33M9T0kr53a0xrfu7_v9-gE0Lcjr
description: |
  A simple app that demonstrates how to setup Helix with knowledge from the Helix docs
assistants:
- name: Helix
  model: llama3.1:8b-instruct-q8_0
  system_prompt: |
    You are an expert at answering questions about the website https://docs.helixml.tech/ and how to
    run the Helix platform. Make sure your answers are very detailed and comprehensive. Use
    as much background knowledge as possible to answer the question and provide creative ways
    to resolve the question.
  knowledge:
  - name: helix-docs
    refresh_enabled: true
    refresh_schedule: "0 0 * * *"
    rag_settings:
      results_count: 8
      chunk_size: 2048
    source:
      web:
        urls:
        - https://docs.helixml.tech/helix/
        excludes:
        - searchbot/*
        crawler:
          enabled: true

triggers:
- discord:
    server_name: "HelixML"