// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAppUpdate() {
  return window['go']['main']['App']['ApplyAppUpdate']();
}

export function ApplyCombinedUpdate() {
  return window['go']['main']['App']['ApplyCombinedUpdate']();
}

export function ApplyVMUpdate() {
  return window['go']['main']['App']['ApplyVMUpdate']();
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CancelUpdate() {
  return window['go']['main']['App']['CancelUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DownloadVMImages() {
  return window['go']['main']['App']['DownloadVMImages']();
}

export function DownloadVMUpdate() {
  return window['go']['main']['App']['DownloadVMUpdate']();
}

export function FactoryReset(arg1) {
  return window['go']['main']['App']['FactoryReset'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutoLoginURL() {
  return window['go']['main']['App']['GetAutoLoginURL']();
}

export function GetConsoleOutput() {
  return window['go']['main']['App']['GetConsoleOutput']();
}

export function GetConsolePassword() {
  return window['go']['main']['App']['GetConsolePassword']();
}

export function GetDesktopQuota() {
  return window['go']['main']['App']['GetDesktopQuota']();
}

export function GetDiskUsage() {
  return window['go']['main']['App']['GetDiskUsage']();
}

export function GetDownloadStatus() {
  return window['go']['main']['App']['GetDownloadStatus']();
}

export function GetHelixURL() {
  return window['go']['main']['App']['GetHelixURL']();
}

export function GetLANAddress() {
  return window['go']['main']['App']['GetLANAddress']();
}

export function GetLicenseStatus() {
  return window['go']['main']['App']['GetLicenseStatus']();
}

export function GetLogsOutput() {
  return window['go']['main']['App']['GetLogsOutput']();
}

export function GetSSHCommand() {
  return window['go']['main']['App']['GetSSHCommand']();
}

export function GetScanoutStats() {
  return window['go']['main']['App']['GetScanoutStats']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetUpdateInfo() {
  return window['go']['main']['App']['GetUpdateInfo']();
}

export function GetVMConfig() {
  return window['go']['main']['App']['GetVMConfig']();
}

export function GetVMStatus() {
  return window['go']['main']['App']['GetVMStatus']();
}

export function GetZFSStats() {
  return window['go']['main']['App']['GetZFSStats']();
}

export function IsVMImageReady() {
  return window['go']['main']['App']['IsVMImageReady']();
}

export function IsVMUpdateAvailable() {
  return window['go']['main']['App']['IsVMUpdateAvailable']();
}

export function IsVMUpdateStagedCheck() {
  return window['go']['main']['App']['IsVMUpdateStagedCheck']();
}

export function OpenHelixUI() {
  return window['go']['main']['App']['OpenHelixUI']();
}

export function OpenSession(arg1) {
  return window['go']['main']['App']['OpenSession'](arg1);
}

export function RedownloadVMImage() {
  return window['go']['main']['App']['RedownloadVMImage']();
}

export function ResizeConsole(arg1, arg2) {
  return window['go']['main']['App']['ResizeConsole'](arg1, arg2);
}

export function ResizeDataDisk(arg1) {
  return window['go']['main']['App']['ResizeDataDisk'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendConsoleInput(arg1) {
  return window['go']['main']['App']['SendConsoleInput'](arg1);
}

export function SetCursor(arg1) {
  return window['go']['main']['App']['SetCursor'](arg1);
}

export function SetVMConfig(arg1) {
  return window['go']['main']['App']['SetVMConfig'](arg1);
}

export function StartCombinedUpdate() {
  return window['go']['main']['App']['StartCombinedUpdate']();
}

export function StartTrial() {
  return window['go']['main']['App']['StartTrial']();
}

export function StartVM() {
  return window['go']['main']['App']['StartVM']();
}

export function StopVM() {
  return window['go']['main']['App']['StopVM']();
}

export function ValidateLicenseKey(arg1) {
  return window['go']['main']['App']['ValidateLicenseKey'](arg1);
}
