// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelDownload():Promise<void>;

export function DownloadVMImages():Promise<void>;

export function GetConsoleOutput():Promise<string>;

export function GetDiskUsage():Promise<main.DiskUsage>;

export function GetDownloadStatus():Promise<main.DownloadProgress>;

export function GetHelixURL():Promise<string>;

export function GetLicenseStatus():Promise<main.LicenseStatus>;

export function GetSSHCommand():Promise<string>;

export function GetScanoutStats():Promise<main.ScanoutStats>;

export function GetSettings():Promise<main.AppSettings>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetVMConfig():Promise<main.VMConfig>;

export function GetVMStatus():Promise<main.VMStatus>;

export function GetZFSStats():Promise<main.ZFSStats>;

export function IsVMImageReady():Promise<boolean>;

export function OpenHelixUI():Promise<void>;

export function OpenSession(arg1:string):Promise<void>;

export function ResizeDataDisk(arg1:number):Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SendConsoleInput(arg1:string):Promise<void>;

export function SetVMConfig(arg1:main.VMConfig):Promise<void>;

export function StartTrial():Promise<void>;

export function StartVM():Promise<void>;

export function StopVM():Promise<void>;

export function ValidateLicenseKey(arg1:string):Promise<void>;
