import { StreamKeyModifiers, StreamKeys } from "../api_bindings"

export function convertToModifiers(event: KeyboardEvent): number {
    let modifiers = 0;

    if (event.shiftKey) {
        modifiers |= StreamKeyModifiers.MASK_SHIFT;
    }
    if (event.ctrlKey) {
        modifiers |= StreamKeyModifiers.MASK_CTRL;
    }
    if (event.altKey) {
        modifiers |= StreamKeyModifiers.MASK_ALT;
    }
    if (event.metaKey) {
        modifiers |= StreamKeyModifiers.MASK_META;
    }

    return modifiers
}

// WHY: https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values
const VK_MAPPINGS: Record<string, number | null> = {
    /* Values on Windows */
    Unidentified: null,
    Escape: StreamKeys.VK_ESCAPE,
    Digit1: StreamKeys.VK_KEY_1,
    Digit2: StreamKeys.VK_KEY_2,
    Digit3: StreamKeys.VK_KEY_3,
    Digit4: StreamKeys.VK_KEY_4,
    Digit5: StreamKeys.VK_KEY_5,
    Digit6: StreamKeys.VK_KEY_6,
    Digit7: StreamKeys.VK_KEY_7,
    Digit8: StreamKeys.VK_KEY_8,
    Digit9: StreamKeys.VK_KEY_9,
    Digit0: StreamKeys.VK_KEY_0,
    Minus: StreamKeys.VK_OEM_MINUS,
    Equal: StreamKeys.VK_OEM_PLUS,
    Backspace: StreamKeys.VK_BACK,
    Tab: StreamKeys.VK_TAB,
    KeyQ: StreamKeys.VK_KEY_Q,
    KeyW: StreamKeys.VK_KEY_W,
    KeyE: StreamKeys.VK_KEY_E,
    KeyR: StreamKeys.VK_KEY_R,
    KeyT: StreamKeys.VK_KEY_T,
    KeyY: StreamKeys.VK_KEY_Y,
    KeyU: StreamKeys.VK_KEY_U,
    KeyI: StreamKeys.VK_KEY_I,
    KeyO: StreamKeys.VK_KEY_O,
    KeyP: StreamKeys.VK_KEY_P,
    BracketLeft: StreamKeys.VK_OEM_4,
    BracketRight: StreamKeys.VK_OEM_6,
    Enter: StreamKeys.VK_RETURN,
    ControlLeft: StreamKeys.VK_LCONTROL,
    KeyA: StreamKeys.VK_KEY_A,
    KeyS: StreamKeys.VK_KEY_S,
    KeyD: StreamKeys.VK_KEY_D,
    KeyF: StreamKeys.VK_KEY_F,
    KeyG: StreamKeys.VK_KEY_G,
    KeyH: StreamKeys.VK_KEY_H,
    KeyJ: StreamKeys.VK_KEY_J,
    KeyK: StreamKeys.VK_KEY_K,
    KeyL: StreamKeys.VK_KEY_L,
    Semicolon: StreamKeys.VK_OEM_1,
    Quote: StreamKeys.VK_OEM_7,
    Backquote: StreamKeys.VK_OEM_3,
    ShiftLeft: StreamKeys.VK_LSHIFT,
    Backslash: StreamKeys.VK_OEM_5,
    KeyZ: StreamKeys.VK_KEY_Z,
    KeyX: StreamKeys.VK_KEY_X,
    KeyC: StreamKeys.VK_KEY_C,
    KeyV: StreamKeys.VK_KEY_V,
    KeyB: StreamKeys.VK_KEY_B,
    KeyN: StreamKeys.VK_KEY_N,
    KeyM: StreamKeys.VK_KEY_M,
    Comma: StreamKeys.VK_OEM_COMMA,
    Period: StreamKeys.VK_OEM_PERIOD,
    Slash: StreamKeys.VK_OEM_2,
    ShiftRight: StreamKeys.VK_RSHIFT,
    NumpadMultiply: StreamKeys.VK_MULTIPLY,
    AltLeft: StreamKeys.VK_LMENU,
    Space: StreamKeys.VK_SPACE,
    CapsLock: StreamKeys.VK_CAPITAL,
    F1: StreamKeys.VK_F1,
    F2: StreamKeys.VK_F2,
    F3: StreamKeys.VK_F3,
    F4: StreamKeys.VK_F4,
    F5: StreamKeys.VK_F5,
    F6: StreamKeys.VK_F6,
    F7: StreamKeys.VK_F7,
    F8: StreamKeys.VK_F8,
    F9: StreamKeys.VK_F9,
    F10: StreamKeys.VK_F10,
    Pause: StreamKeys.VK_PAUSE,
    ScrollLock: StreamKeys.VK_SCROLL,
    Numpad7: StreamKeys.VK_NUMPAD7,
    Numpad8: StreamKeys.VK_NUMPAD8,
    Numpad9: StreamKeys.VK_NUMPAD9,
    NumpadSubtract: StreamKeys.VK_SUBTRACT,
    Numpad4: StreamKeys.VK_NUMPAD4,
    Numpad5: StreamKeys.VK_NUMPAD5,
    Numpad6: StreamKeys.VK_NUMPAD6,
    NumpadAdd: StreamKeys.VK_ADD,
    Numpad1: StreamKeys.VK_NUMPAD1,
    Numpad2: StreamKeys.VK_NUMPAD2,
    Numpad3: StreamKeys.VK_NUMPAD3,
    Numpad0: StreamKeys.VK_NUMPAD0,
    NumpadDecimal: StreamKeys.VK_DECIMAL,
    PrintScreen: StreamKeys.VK_SNAPSHOT,
    IntlBackslash: StreamKeys.VK_OEM_102,
    F11: StreamKeys.VK_F11,
    F12: StreamKeys.VK_F12,
    NumpadEqual: null,
    // ShiftRight: StreamKeys.VK_RSHIFT,
    ControlRight: StreamKeys.VK_RCONTROL,
    AltRight: StreamKeys.VK_RMENU,
    MetaLeft: StreamKeys.VK_LWIN,
    MetaRight: StreamKeys.VK_RWIN,
    ContextMenu: StreamKeys.VK_APPS,
    NumLock: StreamKeys.VK_NUMLOCK,
    NumpadEnter: StreamKeys.VK_RETURN,
    AudioVolumeMute: StreamKeys.VK_VOLUME_MUTE,
    AudioVolumeDown: StreamKeys.VK_VOLUME_DOWN,
    AudioVolumeUp: StreamKeys.VK_VOLUME_UP,
    MediaTrackPrevious: StreamKeys.VK_MEDIA_PREV_TRACK,
    MediaTrackNext: StreamKeys.VK_MEDIA_NEXT_TRACK,
    MediaPlayPause: StreamKeys.VK_MEDIA_PLAY_PAUSE,
    MediaStop: StreamKeys.VK_MEDIA_STOP,
    BrowserHome: StreamKeys.VK_BROWSER_HOME,
    BrowserSearch: StreamKeys.VK_BROWSER_SEARCH,
    BrowserFavorites: StreamKeys.VK_BROWSER_FAVORITES,
    BrowserRefresh: StreamKeys.VK_BROWSER_REFRESH,
    BrowserStop: StreamKeys.VK_BROWSER_STOP,
    BrowserForward: StreamKeys.VK_BROWSER_FORWARD,
    BrowserBack: StreamKeys.VK_BROWSER_BACK,
    LaunchApp1: StreamKeys.VK_LAUNCH_APP1,
    LaunchApp2: StreamKeys.VK_LAUNCH_APP2,
    LaunchMail: StreamKeys.VK_LAUNCH_MAIL,
    MediaSelect: StreamKeys.VK_MEDIA_SELECT,
    Convert: StreamKeys.VK_CONVERT,
    NonConvert: StreamKeys.VK_NONCONVERT,
    KanaMode: StreamKeys.VK_KANA,
    Lang1: StreamKeys.VK_HANGUL,
    Lang2: StreamKeys.VK_JUNJA,
    IntlRo: StreamKeys.VK_OEM_102,
    IntlYen: null,
    NumpadComma: null,
    Power: null,
    Sleep: StreamKeys.VK_SLEEP,
    WakeUp: null,
    Undo: null,
    Paste: null,
    Cut: null,
    Copy: null,
    Eject: null,
    // -- Mac
    // KeyA: StreamKeys.VK_KEY_A,
    // KeyS: StreamKeys.VK_KEY_S,
    // KeyD: StreamKeys.VK_KEY_D,
    // KeyF: StreamKeys.VK_KEY_F,
    // KeyH: StreamKeys.VK_KEY_H,
    // KeyG: StreamKeys.VK_KEY_G,
    // KeyZ: StreamKeys.VK_KEY_Z,
    // KeyX: StreamKeys.VK_KEY_X,
    // KeyC: StreamKeys.VK_KEY_C,
    // KeyV: StreamKeys.VK_KEY_V,
    // IntlBackslash: StreamKeys.VK_OEM_102,
    // KeyB: StreamKeys.VK_KEY_B,
    // KeyQ: StreamKeys.VK_KEY_Q,
    // KeyW: StreamKeys.VK_KEY_W,
    // KeyE: StreamKeys.VK_KEY_E,
    // KeyR: StreamKeys.VK_KEY_R,
    // KeyY: StreamKeys.VK_KEY_Y,
    // KeyT: StreamKeys.VK_KEY_T,
    // Digit1: StreamKeys.VK_KEY_1,
    // Digit2: StreamKeys.VK_KEY_2,
    // Digit3: StreamKeys.VK_KEY_3,
    // Digit4: StreamKeys.VK_KEY_4,
    // Digit6: StreamKeys.VK_KEY_6,
    // Digit5: StreamKeys.VK_KEY_5,
    // Equal: StreamKeys.VK_OEM_PLUS,
    // Digit9: StreamKeys.VK_KEY_9,
    // Digit7: StreamKeys.VK_KEY_7,
    // Minus: StreamKeys.VK_OEM_MINUS,
    // Digit8: StreamKeys.VK_KEY_8,
    // Digit0: StreamKeys.VK_KEY_0,
    // BracketRight: StreamKeys.VK_OEM_6,
    // KeyO: StreamKeys.VK_KEY_O,
    // KeyU: StreamKeys.VK_KEY_U,
    // BracketLeft: StreamKeys.VK_OEM_4,
    // KeyI: StreamKeys.VK_KEY_I,
    // KeyP: StreamKeys.VK_KEY_P,
    // Enter: StreamKeys.VK_RETURN,
    // KeyL: StreamKeys.VK_KEY_L,
    // KeyJ: StreamKeys.VK_KEY_J,
    // Quote: StreamKeys.VK_OEM_7,
    // KeyK: StreamKeys.VK_KEY_K,
    // Semicolon: StreamKeys.VK_OEM_1,
    // Backslash: StreamKeys.VK_OEM_5,
    // Comma: StreamKeys.VK_OEM_COMMA,
    // Slash: StreamKeys.VK_OEM_2,
    // KeyN: StreamKeys.VK_KEY_N,
    // KeyM: StreamKeys.VK_KEY_M,
    // Period: StreamKeys.VK_OEM_PERIOD,
    // Tab: StreamKeys.VK_TAB,
    // Space: StreamKeys.VK_SPACE,
    // Backquote: StreamKeys.VK_OEM_3,
    // Backspace: StreamKeys.VK_BACK,
    // Escape: StreamKeys.VK_ESCAPE,
    // MetaRight: StreamKeys.VK_RWIN,
    // MetaLeft: StreamKeys.VK_LWIN,
    // ShiftLeft: StreamKeys.VK_LSHIFT,
    // CapsLock: StreamKeys.VK_CAPITAL,
    // AltLeft: StreamKeys.VK_LMENU,
    // ControlLeft: StreamKeys.VK_LCONTROL,
    // ShiftRight: StreamKeys.VK_RSHIFT,
    // AltRight: StreamKeys.VK_RMENU,
    // ControlRight: StreamKeys.VK_RCONTROL,
    Fn: null,
    // F17: StreamKeys.VK_F17,
    // NumpadDecimal: StreamKeys.VK_DECIMAL,
    // NumpadMultiply: StreamKeys.VK_MULTIPLY,
    // NumpadAdd: StreamKeys.VK_ADD,
    // NumLock: StreamKeys.VK_NUMLOCK,
    // AudioVolumeUp: StreamKeys.VK_VOLUME_UP,
    // AudioVolumeDown: StreamKeys.VK_VOLUME_DOWN,
    // AudioVolumeMute: StreamKeys.VK_VOLUME_MUTE,
    // NumpadDivide: StreamKeys.VK_DIVIDE,
    // NumpadEnter: StreamKeys.VK_RETURN,
    // NumpadSubtract: StreamKeys.VK_SUBTRACT,
    // F18: StreamKeys.VK_F18,
    // F19: StreamKeys.VK_F19,
    // NumpadEqual: null,
    // Numpad0: StreamKeys.VK_NUMPAD0,
    // Numpad1: StreamKeys.VK_NUMPAD1,
    // Numpad2: StreamKeys.VK_NUMPAD2,
    // Numpad3: StreamKeys.VK_NUMPAD3,
    // Numpad4: StreamKeys.VK_NUMPAD4,
    // Numpad5: StreamKeys.VK_NUMPAD5,
    // Numpad6: StreamKeys.VK_NUMPAD6,
    // Numpad7: StreamKeys.VK_NUMPAD7,
    // F20: StreamKeys.VK_F20,
    // Numpad8: StreamKeys.VK_NUMPAD8,
    // Numpad9: StreamKeys.VK_NUMPAD9,
    // IntlYen: null,
    // IntlRo: null,
    // NumpadComma: null,
    // F5: StreamKeys.VK_F5,
    // F6: StreamKeys.VK_F6,
    // F7: StreamKeys.VK_F7,
    // F3: StreamKeys.VK_F3,
    // F8: StreamKeys.VK_F8,
    // F9: StreamKeys.VK_F9,
    // Lang2: null,
    // F11: StreamKeys.VK_F11,
    // Lang1: null,
    // F13: StreamKeys.VK_F13,
    // F16: StreamKeys.VK_F16,
    // F14: StreamKeys.VK_F14,
    // F10: StreamKeys.VK_F10,
    // ContextMenu: StreamKeys.VK_APPS,
    // F12: StreamKeys.VK_F12,
    // F15: StreamKeys.VK_F15,
    // Help: StreamKeys.VK_HELP,
    // Home: StreamKeys.VK_HOME,
    // PageUp: StreamKeys.VK_PRIOR,
    // Delete: StreamKeys.VK_DELETE,
    // F4: StreamKeys.VK_F4,
    // End: StreamKeys.VK_END,
    // F2: StreamKeys.VK_F2,
    // PageDown: StreamKeys.VK_NEXT,
    // F1: StreamKeys.VK_F1,
    ArrowLeft: StreamKeys.VK_LEFT,
    ArrowRight: StreamKeys.VK_RIGHT,
    ArrowDown: StreamKeys.VK_DOWN,
    ArrowUp: StreamKeys.VK_UP,
    // -- Linux
    // Escape: StreamKeys.VK_ESCAPE,
    // Digit1: StreamKeys.VK_KEY_1,
    // Digit2: StreamKeys.VK_KEY_2,
    // Digit3: StreamKeys.VK_KEY_3,
    // Digit4: StreamKeys.VK_KEY_4,
    // Digit5: StreamKeys.VK_KEY_5,
    // Digit6: StreamKeys.VK_KEY_6,
    // Digit7: StreamKeys.VK_KEY_7,
    // Digit8: StreamKeys.VK_KEY_8,
    // Digit9: StreamKeys.VK_KEY_9,
    // Digit0: StreamKeys.VK_KEY_0,
    // Minus: StreamKeys.VK_OEM_MINUS,
    // Equal: StreamKeys.VK_OEM_PLUS,
    // Backspace: StreamKeys.VK_BACK,
    // Tab: StreamKeys.VK_TAB,
    // KeyQ: StreamKeys.VK_KEY_Q,
    // KeyW: StreamKeys.VK_KEY_W,
    // KeyE: StreamKeys.VK_KEY_E,
    // KeyR: StreamKeys.VK_KEY_R,
    // KeyT: StreamKeys.VK_KEY_T,
    // KeyY: StreamKeys.VK_KEY_Y,
    // KeyU: StreamKeys.VK_KEY_U,
    // KeyI: StreamKeys.VK_KEY_I,
    // KeyO: StreamKeys.VK_KEY_O,
    // KeyP: StreamKeys.VK_KEY_P,
    // BracketLeft: StreamKeys.VK_OEM_4,
    // BracketRight: StreamKeys.VK_OEM_6,
    // Enter: StreamKeys.VK_RETURN,
    // ControlLeft: StreamKeys.VK_LCONTROL,
    // KeyA: StreamKeys.VK_KEY_A,
    // KeyS: StreamKeys.VK_KEY_S,
    // KeyD: StreamKeys.VK_KEY_D,
    // KeyF: StreamKeys.VK_KEY_F,
    // KeyG: StreamKeys.VK_KEY_G,
    // KeyH: StreamKeys.VK_KEY_H,
    // KeyJ: StreamKeys.VK_KEY_J,
    // KeyK: StreamKeys.VK_KEY_K,
    // KeyL: StreamKeys.VK_KEY_L,
    // Semicolon: StreamKeys.VK_OEM_1,
    // Quote: StreamKeys.VK_OEM_7,
    // Backquote: StreamKeys.VK_OEM_3,
    // ShiftLeft: StreamKeys.VK_LSHIFT,
    // Backslash: StreamKeys.VK_OEM_5,
    // KeyZ: StreamKeys.VK_KEY_Z,
    // KeyX: StreamKeys.VK_KEY_X,
    // KeyC: StreamKeys.VK_KEY_C,
    // KeyV: StreamKeys.VK_KEY_V,
    // KeyB: StreamKeys.VK_KEY_B,
    // KeyN: StreamKeys.VK_KEY_N,
    // KeyM: StreamKeys.VK_KEY_M,
    // Comma: StreamKeys.VK_OEM_COMMA,
    // Period: StreamKeys.VK_OEM_PERIOD,
    // Slash: StreamKeys.VK_OEM_2,
    // ShiftRight: StreamKeys.VK_RSHIFT,
    // NumpadMultiply: StreamKeys.VK_MULTIPLY,
    // AltLeft: StreamKeys.VK_LMENU,
    // Space: StreamKeys.VK_SPACE,
    // CapsLock: StreamKeys.VK_CAPITAL,
    // F1: StreamKeys.VK_F1,
    // F2: StreamKeys.VK_F2,
    // F3: StreamKeys.VK_F3,
    // F4: StreamKeys.VK_F4,
    // F5: StreamKeys.VK_F5,
    // F6: StreamKeys.VK_F6,
    // F7: StreamKeys.VK_F7,
    // F8: StreamKeys.VK_F8,
    // F9: StreamKeys.VK_F9,
    // F10: StreamKeys.VK_F10,
    // NumLock: StreamKeys.VK_NUMLOCK,
    // ScrollLock: StreamKeys.VK_SCROLL,
    // Numpad7: StreamKeys.VK_NUMPAD7,
    // Numpad8: StreamKeys.VK_NUMPAD8,
    // Numpad9: StreamKeys.VK_NUMPAD9,
    // NumpadSubtract: StreamKeys.VK_SUBTRACT,
    // Numpad4: StreamKeys.VK_NUMPAD4,
    // Numpad5: StreamKeys.VK_NUMPAD5,
    // Numpad6: StreamKeys.VK_NUMPAD6,
    // NumpadAdd: StreamKeys.VK_ADD,
    // Numpad1: StreamKeys.VK_NUMPAD1,
    // Numpad2: StreamKeys.VK_NUMPAD2,
    // Numpad3: StreamKeys.VK_NUMPAD3,
    // Numpad0: StreamKeys.VK_NUMPAD0,
    // NumpadDecimal: StreamKeys.VK_DECIMAL,
    // Unidentified: null,
    // IntlBackslash: StreamKeys.VK_OEM_102,
    // F11: StreamKeys.VK_F11,
    // F12: StreamKeys.VK_F12,
    // IntlRo: null,
    // Convert: StreamKeys.VK_CONVERT,
    // KanaMode: StreamKeys.VK_KANJI,
    // NonConvert: StreamKeys.VK_NONCONVERT,
    // NumpadEnter: StreamKeys.VK_RETURN,
    // ControlRight: StreamKeys.VK_RCONTROL,
    // NumpadDivide: StreamKeys.VK_DIVIDE,
    // PrintScreen: StreamKeys.VK_SNAPSHOT,
    // AltRight: StreamKeys.VK_RMENU,
    // Home: StreamKeys.VK_HOME,
    // ArrowUp: StreamKeys.VK_UP,
    // PageUp: StreamKeys.VK_PRIOR,
    // ArrowLeft: StreamKeys.VK_LEFT,
    // ArrowRight: StreamKeys.VK_RIGHT,
    // End: StreamKeys.VK_END,
    // ArrowDown: StreamKeys.VK_DOWN,
    // PageDown: StreamKeys.VK_NEXT,
    // Insert: StreamKeys.VK_INSERT,
    // Delete: StreamKeys.VK_DELETE,
    VolumeMute: StreamKeys.VK_VOLUME_MUTE,
    // VolumeDown: StreamKeys.VK_VOLUME_DOWN,
    // VolumeUp: StreamKeys.VK_VOLUME_UP,
    // NumpadEqual: null,
    // Pause: StreamKeys.VK_PAUSE,
    // NumpadComma: null,
    // Lang1: null,
    // Lang2: null,
    // IntlYen: null,
    // MetaLeft: StreamKeys.VK_LWIN,
    // MetaRight: StreamKeys.VK_RWIN,
    // ContextMenu: StreamKeys.VK_APPS,
    // BrowserStop: StreamKeys.VK_BROWSER_STOP,
    Again: null,
    // Undo: null,
    Select: StreamKeys.VK_SELECT,
    // Copy: null,
    Open: null,
    // Paste: null,
    Find: null,
    // Cut: null,
    // Help: StreamKeys.VK_HELP,
    // LaunchApp2: StreamKeys.VK_LAUNCH_APP2,
    // Sleep: StreamKeys.VK_SLEEP,
    // WakeUp: null,
    // LaunchApp1: StreamKeys.VK_LAUNCH_APP1,
    // LaunchMail: StreamKeys.VK_LAUNCH_MAIL,
    // BrowserFavorites: StreamKeys.VK_BROWSER_FAVORITES,
    // BrowserBack: StreamKeys.VK_BROWSER_BACK,
    // BrowserForward: StreamKeys.VK_BROWSER_FORWARD,
    // Eject: null,
    // MediaTrackNext: StreamKeys.VK_MEDIA_NEXT_TRACK,
    // MediaPlayPause: StreamKeys.VK_MEDIA_PLAY_PAUSE,
    // MediaTrackPrevious: StreamKeys.VK_MEDIA_PREV_TRACK,
    // MediaStop: StreamKeys.VK_MEDIA_STOP,
    // MediaSelect: StreamKeys.VK_MEDIA_SELECT,
    // BrowserHome: StreamKeys.VK_BROWSER_HOME,
    // BrowserRefresh: StreamKeys.VK_BROWSER_REFRESH,
    // F13: StreamKeys.VK_F13,
    // F14: StreamKeys.VK_F14,
    // F15: StreamKeys.VK_F15,
    // F16: StreamKeys.VK_F16,
    // F17: StreamKeys.VK_F17,
    // F18: StreamKeys.VK_F18,
    // F19: StreamKeys.VK_F19,
    // F20: StreamKeys.VK_F20,
    // F21: StreamKeys.VK_F21,
    // F22: StreamKeys.VK_F22,
    // F23: StreamKeys.VK_F23,
    // F24: StreamKeys.VK_F24,
    // BrowserSearch: StreamKeys.VK_BROWSER_SEARCH,
    // -- Android
    // Escape: StreamKeys.VK_ESCAPE,
    // Digit1: StreamKeys.VK_KEY_1,
    // Digit2: StreamKeys.VK_KEY_2,
    // Digit3: StreamKeys.VK_KEY_3,
    // Digit4: StreamKeys.VK_KEY_4,
    // Digit5: StreamKeys.VK_KEY_5,
    // Digit6: StreamKeys.VK_KEY_6,
    // Digit7: StreamKeys.VK_KEY_7,
    // Digit8: StreamKeys.VK_KEY_8,
    // Digit9: StreamKeys.VK_KEY_9,
    // Digit0: StreamKeys.VK_KEY_0,
    // Minus: StreamKeys.VK_OEM_MINUS,
    // Equal: StreamKeys.VK_OEM_PLUS,
    // Backspace: StreamKeys.VK_BACK,
    // Tab: StreamKeys.VK_TAB,
    // KeyQ: StreamKeys.VK_KEY_Q,
    // KeyW: StreamKeys.VK_KEY_W,
    // KeyE: StreamKeys.VK_KEY_E,
    // KeyR: StreamKeys.VK_KEY_R,
    // KeyT: StreamKeys.VK_KEY_T,
    // KeyY: StreamKeys.VK_KEY_Y,
    // KeyU: StreamKeys.VK_KEY_U,
    // KeyI: StreamKeys.VK_KEY_I,
    // KeyO: StreamKeys.VK_KEY_O,
    // KeyP: StreamKeys.VK_KEY_P,
    // BracketLeft: StreamKeys.VK_OEM_4,
    // BracketRight: StreamKeys.VK_OEM_6,
    // Enter: StreamKeys.VK_RETURN,
    // ControlLeft: StreamKeys.VK_LCONTROL,
    // KeyA: StreamKeys.VK_KEY_A,
    // KeyS: StreamKeys.VK_KEY_S,
    // KeyD: StreamKeys.VK_KEY_D,
    // KeyF: StreamKeys.VK_KEY_F,
    // KeyG: StreamKeys.VK_KEY_G,
    // KeyH: StreamKeys.VK_KEY_H,
    // KeyJ: StreamKeys.VK_KEY_J,
    // KeyK: StreamKeys.VK_KEY_K,
    // KeyL: StreamKeys.VK_KEY_L,
    // Semicolon: StreamKeys.VK_OEM_1,
    // Quote: StreamKeys.VK_OEM_7,
    // Backquote: StreamKeys.VK_OEM_3,
    // ShiftLeft: StreamKeys.VK_LSHIFT,
    // Backslash: StreamKeys.VK_OEM_5,
    // KeyZ: StreamKeys.VK_KEY_Z,
    // KeyX: StreamKeys.VK_KEY_X,
    // KeyC: StreamKeys.VK_KEY_C,
    // KeyV: StreamKeys.VK_KEY_V,
    // KeyB: StreamKeys.VK_KEY_B,
    // KeyN: StreamKeys.VK_KEY_N,
    // KeyM: StreamKeys.VK_KEY_M,
    // Comma: StreamKeys.VK_OEM_COMMA,
    // Period: StreamKeys.VK_OEM_PERIOD,
    // Slash: StreamKeys.VK_OEM_2,
    // ShiftRight: StreamKeys.VK_RSHIFT,
    // NumpadMultiply: StreamKeys.VK_MULTIPLY,
    // AltLeft: StreamKeys.VK_LMENU,
    // Space: StreamKeys.VK_SPACE,
    // CapsLock: StreamKeys.VK_CAPITAL,
    // F1: StreamKeys.VK_F1,
    // F2: StreamKeys.VK_F2,
    // F3: StreamKeys.VK_F3,
    // F4: StreamKeys.VK_F4,
    // F5: StreamKeys.VK_F5,
    // F6: StreamKeys.VK_F6,
    // F7: StreamKeys.VK_F7,
    // F8: StreamKeys.VK_F8,
    // F9: StreamKeys.VK_F9,
    // F10: StreamKeys.VK_F10,
    // NumLock: StreamKeys.VK_NUMLOCK,
    // ScrollLock: StreamKeys.VK_SCROLL,
    // Numpad7: StreamKeys.VK_NUMPAD7,
    // Numpad8: StreamKeys.VK_NUMPAD8,
    // Numpad9: StreamKeys.VK_NUMPAD9,
    // NumpadSubtract: StreamKeys.VK_SUBTRACT,
    // Numpad4: StreamKeys.VK_NUMPAD4,
    // Numpad5: StreamKeys.VK_NUMPAD5,
    // Numpad6: StreamKeys.VK_NUMPAD6,
    // NumpadAdd: StreamKeys.VK_ADD,
    // Numpad1: StreamKeys.VK_NUMPAD1,
    // Numpad2: StreamKeys.VK_NUMPAD2,
    // Numpad3: StreamKeys.VK_NUMPAD3,
    // Numpad0: StreamKeys.VK_NUMPAD0,
    // NumpadDecimal: StreamKeys.VK_DECIMAL,
    // Unidentified: null,
    // IntlBackslash: StreamKeys.VK_OEM_102,
    // F11: StreamKeys.VK_F11,
    // F12: StreamKeys.VK_F12,
    // IntlRo: null,
    // Convert: StreamKeys.VK_CONVERT,
    // KanaMode: StreamKeys.VK_KANJI,
    // NonConvert: StreamKeys.VK_NONCONVERT,
    // NumpadEnter: StreamKeys.VK_RETURN,
    // ControlRight: StreamKeys.VK_RCONTROL,
    // NumpadDivide: StreamKeys.VK_DIVIDE,
    // PrintScreen: StreamKeys.VK_SNAPSHOT,
    // AltRight: StreamKeys.VK_RMENU,
    // Home: StreamKeys.VK_HOME,
    // ArrowUp: StreamKeys.VK_UP,
    // PageUp: StreamKeys.VK_PRIOR,
    // ArrowLeft: StreamKeys.VK_LEFT,
    // ArrowRight: StreamKeys.VK_RIGHT,
    // End: StreamKeys.VK_END,
    // ArrowDown: StreamKeys.VK_DOWN,
    // PageDown: StreamKeys.VK_NEXT,
    // Insert: StreamKeys.VK_INSERT,
    // Delete: StreamKeys.VK_DELETE,
    // VolumeMute: StreamKeys.VK_VOLUME_MUTE,
    // VolumeDown: StreamKeys.VK_VOLUME_DOWN,
    // VolumeUp: StreamKeys.VK_VOLUME_UP,
    // Power: null,
    // NumpadEqual: null,
    // Pause: StreamKeys.VK_PAUSE,
    // NumpadComma: null,
    // Lang1: null,
    // Lang2: null,
    // IntlYen: null,
    // MetaLeft: StreamKeys.VK_LWIN,
    // MetaRight: StreamKeys.VK_RWIN,
    // ContextMenu: StreamKeys.VK_APPS,
    // BrowserStop: StreamKeys.VK_BROWSER_STOP,
    // Again: null,
    Props: null,
    // Undo: null,
    // Select: StreamKeys.VK_SELECT,
    // Copy: null,
    // Open: null,
    // Paste: null,
    // Find: null,
    // Cut: null,
    // Help: StreamKeys.VK_HELP,
    // Sleep: StreamKeys.VK_SLEEP,
    // WakeUp: null,
    // LaunchApp1: StreamKeys.VK_LAUNCH_APP1,
    // BrowserFavorites: StreamKeys.VK_BROWSER_FAVORITES,
    // BrowserBack: StreamKeys.VK_BROWSER_BACK,
    // BrowserForward: StreamKeys.VK_BROWSER_FORWARD,
    // Eject: null,
    // MediaTrackNext: StreamKeys.VK_MEDIA_NEXT_TRACK,
    // MediaPlayPause: StreamKeys.VK_MEDIA_PLAY_PAUSE,
    // MediaTrackPrevious: StreamKeys.VK_MEDIA_PREV_TRACK,
    // MediaStop: StreamKeys.VK_MEDIA_STOP,
    // BrowserRefresh: StreamKeys.VK_BROWSER_REFRESH,
    // F13: StreamKeys.VK_F13,
    // F14: StreamKeys.VK_F14,
    // F15: StreamKeys.VK_F15,
    // F16: StreamKeys.VK_F16,
    // F17: StreamKeys.VK_F17,
    // F18: StreamKeys.VK_F18,
    // F19: StreamKeys.VK_F19,
    // F20: StreamKeys.VK_F20,
    // F21: StreamKeys.VK_F21,
    // F22: StreamKeys.VK_F22,
    // F23: StreamKeys.VK_F23,
    // F24: StreamKeys.VK_F24,
    // BrowserSearch: StreamKeys.VK_BROWSER_SEARCH,
    // Fn: null,
}

/**
 * Fallback mappings for event.key values (single characters).
 * This handles iPad/iOS where event.code is empty for alphanumeric keys
 * but event.key contains the actual character.
 */
const KEY_VALUE_MAPPINGS: Record<string, number> = {
    // Letters (both lowercase and uppercase map to same VK code)
    'a': StreamKeys.VK_KEY_A, 'A': StreamKeys.VK_KEY_A,
    'b': StreamKeys.VK_KEY_B, 'B': StreamKeys.VK_KEY_B,
    'c': StreamKeys.VK_KEY_C, 'C': StreamKeys.VK_KEY_C,
    'd': StreamKeys.VK_KEY_D, 'D': StreamKeys.VK_KEY_D,
    'e': StreamKeys.VK_KEY_E, 'E': StreamKeys.VK_KEY_E,
    'f': StreamKeys.VK_KEY_F, 'F': StreamKeys.VK_KEY_F,
    'g': StreamKeys.VK_KEY_G, 'G': StreamKeys.VK_KEY_G,
    'h': StreamKeys.VK_KEY_H, 'H': StreamKeys.VK_KEY_H,
    'i': StreamKeys.VK_KEY_I, 'I': StreamKeys.VK_KEY_I,
    'j': StreamKeys.VK_KEY_J, 'J': StreamKeys.VK_KEY_J,
    'k': StreamKeys.VK_KEY_K, 'K': StreamKeys.VK_KEY_K,
    'l': StreamKeys.VK_KEY_L, 'L': StreamKeys.VK_KEY_L,
    'm': StreamKeys.VK_KEY_M, 'M': StreamKeys.VK_KEY_M,
    'n': StreamKeys.VK_KEY_N, 'N': StreamKeys.VK_KEY_N,
    'o': StreamKeys.VK_KEY_O, 'O': StreamKeys.VK_KEY_O,
    'p': StreamKeys.VK_KEY_P, 'P': StreamKeys.VK_KEY_P,
    'q': StreamKeys.VK_KEY_Q, 'Q': StreamKeys.VK_KEY_Q,
    'r': StreamKeys.VK_KEY_R, 'R': StreamKeys.VK_KEY_R,
    's': StreamKeys.VK_KEY_S, 'S': StreamKeys.VK_KEY_S,
    't': StreamKeys.VK_KEY_T, 'T': StreamKeys.VK_KEY_T,
    'u': StreamKeys.VK_KEY_U, 'U': StreamKeys.VK_KEY_U,
    'v': StreamKeys.VK_KEY_V, 'V': StreamKeys.VK_KEY_V,
    'w': StreamKeys.VK_KEY_W, 'W': StreamKeys.VK_KEY_W,
    'x': StreamKeys.VK_KEY_X, 'X': StreamKeys.VK_KEY_X,
    'y': StreamKeys.VK_KEY_Y, 'Y': StreamKeys.VK_KEY_Y,
    'z': StreamKeys.VK_KEY_Z, 'Z': StreamKeys.VK_KEY_Z,
    // Numbers
    '0': StreamKeys.VK_KEY_0,
    '1': StreamKeys.VK_KEY_1,
    '2': StreamKeys.VK_KEY_2,
    '3': StreamKeys.VK_KEY_3,
    '4': StreamKeys.VK_KEY_4,
    '5': StreamKeys.VK_KEY_5,
    '6': StreamKeys.VK_KEY_6,
    '7': StreamKeys.VK_KEY_7,
    '8': StreamKeys.VK_KEY_8,
    '9': StreamKeys.VK_KEY_9,
    // Shift+number symbols (US keyboard layout)
    '!': StreamKeys.VK_KEY_1,
    '@': StreamKeys.VK_KEY_2,
    '#': StreamKeys.VK_KEY_3,
    '$': StreamKeys.VK_KEY_4,
    '%': StreamKeys.VK_KEY_5,
    '^': StreamKeys.VK_KEY_6,
    '&': StreamKeys.VK_KEY_7,
    '*': StreamKeys.VK_KEY_8,
    '(': StreamKeys.VK_KEY_9,
    ')': StreamKeys.VK_KEY_0,
    // Common punctuation
    '-': StreamKeys.VK_OEM_MINUS,
    '_': StreamKeys.VK_OEM_MINUS,
    '=': StreamKeys.VK_OEM_PLUS,
    '+': StreamKeys.VK_OEM_PLUS,
    '[': StreamKeys.VK_OEM_4,
    '{': StreamKeys.VK_OEM_4,
    ']': StreamKeys.VK_OEM_6,
    '}': StreamKeys.VK_OEM_6,
    '\\': StreamKeys.VK_OEM_5,
    '|': StreamKeys.VK_OEM_5,
    ';': StreamKeys.VK_OEM_1,
    ':': StreamKeys.VK_OEM_1,
    "'": StreamKeys.VK_OEM_7,
    '"': StreamKeys.VK_OEM_7,
    '`': StreamKeys.VK_OEM_3,
    '~': StreamKeys.VK_OEM_3,
    ',': StreamKeys.VK_OEM_COMMA,
    '<': StreamKeys.VK_OEM_COMMA,
    '.': StreamKeys.VK_OEM_PERIOD,
    '>': StreamKeys.VK_OEM_PERIOD,
    '/': StreamKeys.VK_OEM_2,
    '?': StreamKeys.VK_OEM_2,
    ' ': StreamKeys.VK_SPACE,

    // === International character support ===
    // These map accented characters to their base letter keys.
    // The remote desktop won't receive the accent, but input won't be dropped.

    // French accented characters
    'é': StreamKeys.VK_KEY_E, 'É': StreamKeys.VK_KEY_E,
    'è': StreamKeys.VK_KEY_E, 'È': StreamKeys.VK_KEY_E,
    'ê': StreamKeys.VK_KEY_E, 'Ê': StreamKeys.VK_KEY_E,
    'ë': StreamKeys.VK_KEY_E, 'Ë': StreamKeys.VK_KEY_E,
    'à': StreamKeys.VK_KEY_A, 'À': StreamKeys.VK_KEY_A,
    'â': StreamKeys.VK_KEY_A, 'Â': StreamKeys.VK_KEY_A,
    'ù': StreamKeys.VK_KEY_U, 'Ù': StreamKeys.VK_KEY_U,
    'û': StreamKeys.VK_KEY_U, 'Û': StreamKeys.VK_KEY_U,
    'ü': StreamKeys.VK_KEY_U, 'Ü': StreamKeys.VK_KEY_U,
    'î': StreamKeys.VK_KEY_I, 'Î': StreamKeys.VK_KEY_I,
    'ï': StreamKeys.VK_KEY_I, 'Ï': StreamKeys.VK_KEY_I,
    'ô': StreamKeys.VK_KEY_O, 'Ô': StreamKeys.VK_KEY_O,
    'ç': StreamKeys.VK_KEY_C, 'Ç': StreamKeys.VK_KEY_C,
    'œ': StreamKeys.VK_KEY_O, 'Œ': StreamKeys.VK_KEY_O,
    'æ': StreamKeys.VK_KEY_A, 'Æ': StreamKeys.VK_KEY_A,

    // German special characters
    'ä': StreamKeys.VK_KEY_A, 'Ä': StreamKeys.VK_KEY_A,
    'ö': StreamKeys.VK_KEY_O, 'Ö': StreamKeys.VK_KEY_O,
    'ß': StreamKeys.VK_KEY_S, 'ẞ': StreamKeys.VK_KEY_S,

    // Spanish special characters
    'ñ': StreamKeys.VK_KEY_N, 'Ñ': StreamKeys.VK_KEY_N,
    'á': StreamKeys.VK_KEY_A, 'Á': StreamKeys.VK_KEY_A,
    'í': StreamKeys.VK_KEY_I, 'Í': StreamKeys.VK_KEY_I,
    'ó': StreamKeys.VK_KEY_O, 'Ó': StreamKeys.VK_KEY_O,
    'ú': StreamKeys.VK_KEY_U, 'Ú': StreamKeys.VK_KEY_U,
    '¿': StreamKeys.VK_OEM_2,  // Map to / key
    '¡': StreamKeys.VK_KEY_1,  // Map to 1 key

    // UK keyboard specifics
    '£': StreamKeys.VK_KEY_3,  // UK Shift+3

    // Common European symbols
    '€': StreamKeys.VK_KEY_E,  // Euro on E key in most EU layouts
    '§': StreamKeys.VK_KEY_S,  // Section sign
    '°': StreamKeys.VK_KEY_0,  // Degree symbol
    // Note: French AZERTY has & é " ' ( - è _ ç à ) = on number keys unshifted
    // These accented chars are already mapped above
}

export function convertToKey(event: KeyboardEvent): number | null {
    // First try event.code (physical key location)
    let key = VK_MAPPINGS[event.code] ?? null
    if (key == null) {
        // Fallback to VK_MAPPINGS with event.key (for named keys like "Escape")
        key = VK_MAPPINGS[event.key] ?? null
    }
    if (key == null) {
        // Final fallback: character-based mapping for iPad/iOS
        // where event.code is empty but event.key has the character
        key = KEY_VALUE_MAPPINGS[event.key] ?? null
    }
    return key
}
