# SSE MCP Test Agent
# Used by scripts/test-zed-sse-mcp.sh to verify Zed SSE MCP transport integration
#
# This agent is configured to use the official MCP server-everything via SSE transport.
# The test verifies the agent can use the echo tool via the legacy SSE transport.

apiVersion: app.aispec.org/v1alpha1
kind: AIApp
metadata:
  name: sse-mcp-test-agent
spec:
  name: sse-mcp-test-agent
  description: Test agent for verifying Zed SSE MCP transport integration
  assistants:
    - name: default
      provider: anthropic
      model: claude-3-5-haiku-20241022
      agent_mode: false
      agent_type: zed_external
      max_iterations: 0
      generation_model_provider: anthropic
      generation_model: claude-sonnet-4-5-20250514
      code_agent_runtime: zed_agent
      system_prompt: |
        You are a helpful assistant with access to MCP tools.
        When asked to echo something, use the echo tool from the everything-server MCP.
        Always report the exact value returned by the tool.
      context_limit: 20
      temperature: 0.1
      top_p: 1
      max_tokens: 2000
      reasoning_effort: none
      mcps:
        - name: everything-server
          description: Official MCP server-everything providing echo and other test tools
          # This URL is accessible from the Helix API via Docker networking
          # The sse-mcp-test container runs on helix_default network
          url: http://sse-mcp-test:3001/sse
          transport: sse  # Use legacy SSE transport (MCP 2024-11-05) instead of Streamable HTTP
      project_manager:
        enabled: false
      browser:
        enabled: false
        markdown_post_processing: false
        process_output: false
        cache: false
        no_browser: false
      web_search:
        enabled: false
        max_results: 0
      calculator:
        enabled: false
      email:
        enabled: false
      azure_devops:
        enabled: false
  default_agent_type: zed_external
  external_agent_config:
    resolution: 1080p
    desktop_type: ubuntu
    zoom_level: 100