// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source store.go -destination store_mocks.go -package store
//

// Package store is a generated GoMock package.
package store

import (
	context "context"
	reflect "reflect"

	license "github.com/helixml/helix/api/pkg/license"
	types "github.com/helixml/helix/api/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateAPIKey mocks base method.
func (m *MockStore) CreateAPIKey(ctx context.Context, apiKey *types.ApiKey) (*types.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPIKey", ctx, apiKey)
	ret0, _ := ret[0].(*types.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAPIKey indicates an expected call of CreateAPIKey.
func (mr *MockStoreMockRecorder) CreateAPIKey(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPIKey", reflect.TypeOf((*MockStore)(nil).CreateAPIKey), ctx, apiKey)
}

// CreateAccessGrant mocks base method.
func (m *MockStore) CreateAccessGrant(ctx context.Context, resourceAccess *types.AccessGrant, roles []*types.Role) (*types.AccessGrant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessGrant", ctx, resourceAccess, roles)
	ret0, _ := ret[0].(*types.AccessGrant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessGrant indicates an expected call of CreateAccessGrant.
func (mr *MockStoreMockRecorder) CreateAccessGrant(ctx, resourceAccess, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessGrant", reflect.TypeOf((*MockStore)(nil).CreateAccessGrant), ctx, resourceAccess, roles)
}

// CreateAccessGrantRoleBinding mocks base method.
func (m *MockStore) CreateAccessGrantRoleBinding(ctx context.Context, binding *types.AccessGrantRoleBinding) (*types.AccessGrantRoleBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessGrantRoleBinding", ctx, binding)
	ret0, _ := ret[0].(*types.AccessGrantRoleBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessGrantRoleBinding indicates an expected call of CreateAccessGrantRoleBinding.
func (mr *MockStoreMockRecorder) CreateAccessGrantRoleBinding(ctx, binding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessGrantRoleBinding", reflect.TypeOf((*MockStore)(nil).CreateAccessGrantRoleBinding), ctx, binding)
}

// CreateApp mocks base method.
func (m *MockStore) CreateApp(ctx context.Context, tool *types.App) (*types.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApp", ctx, tool)
	ret0, _ := ret[0].(*types.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApp indicates an expected call of CreateApp.
func (mr *MockStoreMockRecorder) CreateApp(ctx, tool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApp", reflect.TypeOf((*MockStore)(nil).CreateApp), ctx, tool)
}

// CreateDataEntity mocks base method.
func (m *MockStore) CreateDataEntity(ctx context.Context, dataEntity *types.DataEntity) (*types.DataEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDataEntity", ctx, dataEntity)
	ret0, _ := ret[0].(*types.DataEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDataEntity indicates an expected call of CreateDataEntity.
func (mr *MockStoreMockRecorder) CreateDataEntity(ctx, dataEntity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDataEntity", reflect.TypeOf((*MockStore)(nil).CreateDataEntity), ctx, dataEntity)
}

// CreateKnowledge mocks base method.
func (m *MockStore) CreateKnowledge(ctx context.Context, knowledge *types.Knowledge) (*types.Knowledge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKnowledge", ctx, knowledge)
	ret0, _ := ret[0].(*types.Knowledge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKnowledge indicates an expected call of CreateKnowledge.
func (mr *MockStoreMockRecorder) CreateKnowledge(ctx, knowledge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKnowledge", reflect.TypeOf((*MockStore)(nil).CreateKnowledge), ctx, knowledge)
}

// CreateKnowledgeVersion mocks base method.
func (m *MockStore) CreateKnowledgeVersion(ctx context.Context, version *types.KnowledgeVersion) (*types.KnowledgeVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKnowledgeVersion", ctx, version)
	ret0, _ := ret[0].(*types.KnowledgeVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKnowledgeVersion indicates an expected call of CreateKnowledgeVersion.
func (mr *MockStoreMockRecorder) CreateKnowledgeVersion(ctx, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKnowledgeVersion", reflect.TypeOf((*MockStore)(nil).CreateKnowledgeVersion), ctx, version)
}

// CreateLLMCall mocks base method.
func (m *MockStore) CreateLLMCall(ctx context.Context, call *types.LLMCall) (*types.LLMCall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLLMCall", ctx, call)
	ret0, _ := ret[0].(*types.LLMCall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLLMCall indicates an expected call of CreateLLMCall.
func (mr *MockStoreMockRecorder) CreateLLMCall(ctx, call any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLLMCall", reflect.TypeOf((*MockStore)(nil).CreateLLMCall), ctx, call)
}

// CreateOrganization mocks base method.
func (m *MockStore) CreateOrganization(ctx context.Context, org *types.Organization) (*types.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, org)
	ret0, _ := ret[0].(*types.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockStoreMockRecorder) CreateOrganization(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockStore)(nil).CreateOrganization), ctx, org)
}

// CreateOrganizationMembership mocks base method.
func (m *MockStore) CreateOrganizationMembership(ctx context.Context, membership *types.OrganizationMembership) (*types.OrganizationMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganizationMembership", ctx, membership)
	ret0, _ := ret[0].(*types.OrganizationMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganizationMembership indicates an expected call of CreateOrganizationMembership.
func (mr *MockStoreMockRecorder) CreateOrganizationMembership(ctx, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganizationMembership", reflect.TypeOf((*MockStore)(nil).CreateOrganizationMembership), ctx, membership)
}

// CreateProviderEndpoint mocks base method.
func (m *MockStore) CreateProviderEndpoint(ctx context.Context, providerEndpoint *types.ProviderEndpoint) (*types.ProviderEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProviderEndpoint", ctx, providerEndpoint)
	ret0, _ := ret[0].(*types.ProviderEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProviderEndpoint indicates an expected call of CreateProviderEndpoint.
func (mr *MockStoreMockRecorder) CreateProviderEndpoint(ctx, providerEndpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProviderEndpoint", reflect.TypeOf((*MockStore)(nil).CreateProviderEndpoint), ctx, providerEndpoint)
}

// CreateRole mocks base method.
func (m *MockStore) CreateRole(ctx context.Context, role *types.Role) (*types.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, role)
	ret0, _ := ret[0].(*types.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockStoreMockRecorder) CreateRole(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockStore)(nil).CreateRole), ctx, role)
}

// CreateScriptRun mocks base method.
func (m *MockStore) CreateScriptRun(ctx context.Context, task *types.ScriptRun) (*types.ScriptRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScriptRun", ctx, task)
	ret0, _ := ret[0].(*types.ScriptRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScriptRun indicates an expected call of CreateScriptRun.
func (mr *MockStoreMockRecorder) CreateScriptRun(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScriptRun", reflect.TypeOf((*MockStore)(nil).CreateScriptRun), ctx, task)
}

// CreateSecret mocks base method.
func (m *MockStore) CreateSecret(ctx context.Context, secret *types.Secret) (*types.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecret", ctx, secret)
	ret0, _ := ret[0].(*types.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MockStoreMockRecorder) CreateSecret(ctx, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MockStore)(nil).CreateSecret), ctx, secret)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(ctx context.Context, session types.Session) (*types.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session)
	ret0, _ := ret[0].(*types.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), ctx, session)
}

// CreateTeam mocks base method.
func (m *MockStore) CreateTeam(ctx context.Context, team *types.Team) (*types.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, team)
	ret0, _ := ret[0].(*types.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockStoreMockRecorder) CreateTeam(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockStore)(nil).CreateTeam), ctx, team)
}

// CreateTool mocks base method.
func (m *MockStore) CreateTool(ctx context.Context, tool *types.Tool) (*types.Tool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTool", ctx, tool)
	ret0, _ := ret[0].(*types.Tool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTool indicates an expected call of CreateTool.
func (mr *MockStoreMockRecorder) CreateTool(ctx, tool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTool", reflect.TypeOf((*MockStore)(nil).CreateTool), ctx, tool)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, user *types.User) (*types.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*types.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, user)
}

// CreateUserMeta mocks base method.
func (m *MockStore) CreateUserMeta(ctx context.Context, UserMeta types.UserMeta) (*types.UserMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserMeta", ctx, UserMeta)
	ret0, _ := ret[0].(*types.UserMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserMeta indicates an expected call of CreateUserMeta.
func (mr *MockStoreMockRecorder) CreateUserMeta(ctx, UserMeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserMeta", reflect.TypeOf((*MockStore)(nil).CreateUserMeta), ctx, UserMeta)
}

// DeleteAPIKey mocks base method.
func (m *MockStore) DeleteAPIKey(ctx context.Context, apiKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAPIKey", ctx, apiKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAPIKey indicates an expected call of DeleteAPIKey.
func (mr *MockStoreMockRecorder) DeleteAPIKey(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAPIKey", reflect.TypeOf((*MockStore)(nil).DeleteAPIKey), ctx, apiKey)
}

// DeleteAccessGrant mocks base method.
func (m *MockStore) DeleteAccessGrant(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessGrant", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessGrant indicates an expected call of DeleteAccessGrant.
func (mr *MockStoreMockRecorder) DeleteAccessGrant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessGrant", reflect.TypeOf((*MockStore)(nil).DeleteAccessGrant), ctx, id)
}

// DeleteAccessGrantRoleBinding mocks base method.
func (m *MockStore) DeleteAccessGrantRoleBinding(ctx context.Context, accessGrantID, roleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessGrantRoleBinding", ctx, accessGrantID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessGrantRoleBinding indicates an expected call of DeleteAccessGrantRoleBinding.
func (mr *MockStoreMockRecorder) DeleteAccessGrantRoleBinding(ctx, accessGrantID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessGrantRoleBinding", reflect.TypeOf((*MockStore)(nil).DeleteAccessGrantRoleBinding), ctx, accessGrantID, roleID)
}

// DeleteApp mocks base method.
func (m *MockStore) DeleteApp(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApp", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApp indicates an expected call of DeleteApp.
func (mr *MockStoreMockRecorder) DeleteApp(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApp", reflect.TypeOf((*MockStore)(nil).DeleteApp), ctx, id)
}

// DeleteDataEntity mocks base method.
func (m *MockStore) DeleteDataEntity(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDataEntity", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDataEntity indicates an expected call of DeleteDataEntity.
func (mr *MockStoreMockRecorder) DeleteDataEntity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDataEntity", reflect.TypeOf((*MockStore)(nil).DeleteDataEntity), ctx, id)
}

// DeleteKnowledge mocks base method.
func (m *MockStore) DeleteKnowledge(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKnowledge", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKnowledge indicates an expected call of DeleteKnowledge.
func (mr *MockStoreMockRecorder) DeleteKnowledge(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKnowledge", reflect.TypeOf((*MockStore)(nil).DeleteKnowledge), ctx, id)
}

// DeleteKnowledgeVersion mocks base method.
func (m *MockStore) DeleteKnowledgeVersion(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKnowledgeVersion", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKnowledgeVersion indicates an expected call of DeleteKnowledgeVersion.
func (mr *MockStoreMockRecorder) DeleteKnowledgeVersion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKnowledgeVersion", reflect.TypeOf((*MockStore)(nil).DeleteKnowledgeVersion), ctx, id)
}

// DeleteOrganization mocks base method.
func (m *MockStore) DeleteOrganization(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganization", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganization indicates an expected call of DeleteOrganization.
func (mr *MockStoreMockRecorder) DeleteOrganization(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganization", reflect.TypeOf((*MockStore)(nil).DeleteOrganization), ctx, id)
}

// DeleteOrganizationMembership mocks base method.
func (m *MockStore) DeleteOrganizationMembership(ctx context.Context, organizationID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganizationMembership", ctx, organizationID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganizationMembership indicates an expected call of DeleteOrganizationMembership.
func (mr *MockStoreMockRecorder) DeleteOrganizationMembership(ctx, organizationID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganizationMembership", reflect.TypeOf((*MockStore)(nil).DeleteOrganizationMembership), ctx, organizationID, userID)
}

// DeleteProviderEndpoint mocks base method.
func (m *MockStore) DeleteProviderEndpoint(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProviderEndpoint", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProviderEndpoint indicates an expected call of DeleteProviderEndpoint.
func (mr *MockStoreMockRecorder) DeleteProviderEndpoint(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProviderEndpoint", reflect.TypeOf((*MockStore)(nil).DeleteProviderEndpoint), ctx, id)
}

// DeleteRole mocks base method.
func (m *MockStore) DeleteRole(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockStoreMockRecorder) DeleteRole(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockStore)(nil).DeleteRole), ctx, id)
}

// DeleteScriptRun mocks base method.
func (m *MockStore) DeleteScriptRun(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScriptRun", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScriptRun indicates an expected call of DeleteScriptRun.
func (mr *MockStoreMockRecorder) DeleteScriptRun(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScriptRun", reflect.TypeOf((*MockStore)(nil).DeleteScriptRun), ctx, id)
}

// DeleteSecret mocks base method.
func (m *MockStore) DeleteSecret(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockStoreMockRecorder) DeleteSecret(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockStore)(nil).DeleteSecret), ctx, id)
}

// DeleteSession mocks base method.
func (m *MockStore) DeleteSession(ctx context.Context, id string) (*types.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, id)
	ret0, _ := ret[0].(*types.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockStoreMockRecorder) DeleteSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockStore)(nil).DeleteSession), ctx, id)
}

// DeleteTeam mocks base method.
func (m *MockStore) DeleteTeam(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeam", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeam indicates an expected call of DeleteTeam.
func (mr *MockStoreMockRecorder) DeleteTeam(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeam", reflect.TypeOf((*MockStore)(nil).DeleteTeam), ctx, id)
}

// DeleteTool mocks base method.
func (m *MockStore) DeleteTool(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTool", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTool indicates an expected call of DeleteTool.
func (mr *MockStoreMockRecorder) DeleteTool(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTool", reflect.TypeOf((*MockStore)(nil).DeleteTool), ctx, id)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), ctx, id)
}

// EnsureUserMeta mocks base method.
func (m *MockStore) EnsureUserMeta(ctx context.Context, UserMeta types.UserMeta) (*types.UserMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureUserMeta", ctx, UserMeta)
	ret0, _ := ret[0].(*types.UserMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureUserMeta indicates an expected call of EnsureUserMeta.
func (mr *MockStoreMockRecorder) EnsureUserMeta(ctx, UserMeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureUserMeta", reflect.TypeOf((*MockStore)(nil).EnsureUserMeta), ctx, UserMeta)
}

// GetAPIKey mocks base method.
func (m *MockStore) GetAPIKey(ctx context.Context, apiKey string) (*types.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIKey", ctx, apiKey)
	ret0, _ := ret[0].(*types.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAPIKey indicates an expected call of GetAPIKey.
func (mr *MockStoreMockRecorder) GetAPIKey(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIKey", reflect.TypeOf((*MockStore)(nil).GetAPIKey), ctx, apiKey)
}

// GetAccessGrantRoleBindings mocks base method.
func (m *MockStore) GetAccessGrantRoleBindings(ctx context.Context, q *GetAccessGrantRoleBindingsQuery) ([]*types.AccessGrantRoleBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessGrantRoleBindings", ctx, q)
	ret0, _ := ret[0].([]*types.AccessGrantRoleBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessGrantRoleBindings indicates an expected call of GetAccessGrantRoleBindings.
func (mr *MockStoreMockRecorder) GetAccessGrantRoleBindings(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessGrantRoleBindings", reflect.TypeOf((*MockStore)(nil).GetAccessGrantRoleBindings), ctx, q)
}

// GetApp mocks base method.
func (m *MockStore) GetApp(ctx context.Context, id string) (*types.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApp", ctx, id)
	ret0, _ := ret[0].(*types.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApp indicates an expected call of GetApp.
func (mr *MockStoreMockRecorder) GetApp(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApp", reflect.TypeOf((*MockStore)(nil).GetApp), ctx, id)
}

// GetAppWithTools mocks base method.
func (m *MockStore) GetAppWithTools(ctx context.Context, id string) (*types.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppWithTools", ctx, id)
	ret0, _ := ret[0].(*types.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppWithTools indicates an expected call of GetAppWithTools.
func (mr *MockStoreMockRecorder) GetAppWithTools(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppWithTools", reflect.TypeOf((*MockStore)(nil).GetAppWithTools), ctx, id)
}

// GetDataEntity mocks base method.
func (m *MockStore) GetDataEntity(ctx context.Context, id string) (*types.DataEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataEntity", ctx, id)
	ret0, _ := ret[0].(*types.DataEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataEntity indicates an expected call of GetDataEntity.
func (mr *MockStoreMockRecorder) GetDataEntity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataEntity", reflect.TypeOf((*MockStore)(nil).GetDataEntity), ctx, id)
}

// GetDecodedLicense mocks base method.
func (m *MockStore) GetDecodedLicense(ctx context.Context) (*license.License, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDecodedLicense", ctx)
	ret0, _ := ret[0].(*license.License)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDecodedLicense indicates an expected call of GetDecodedLicense.
func (mr *MockStoreMockRecorder) GetDecodedLicense(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDecodedLicense", reflect.TypeOf((*MockStore)(nil).GetDecodedLicense), ctx)
}

// GetKnowledge mocks base method.
func (m *MockStore) GetKnowledge(ctx context.Context, id string) (*types.Knowledge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledge", ctx, id)
	ret0, _ := ret[0].(*types.Knowledge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKnowledge indicates an expected call of GetKnowledge.
func (mr *MockStoreMockRecorder) GetKnowledge(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledge", reflect.TypeOf((*MockStore)(nil).GetKnowledge), ctx, id)
}

// GetKnowledgeVersion mocks base method.
func (m *MockStore) GetKnowledgeVersion(ctx context.Context, id string) (*types.KnowledgeVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeVersion", ctx, id)
	ret0, _ := ret[0].(*types.KnowledgeVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKnowledgeVersion indicates an expected call of GetKnowledgeVersion.
func (mr *MockStoreMockRecorder) GetKnowledgeVersion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeVersion", reflect.TypeOf((*MockStore)(nil).GetKnowledgeVersion), ctx, id)
}

// GetLicenseKey mocks base method.
func (m *MockStore) GetLicenseKey(ctx context.Context) (*types.LicenseKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLicenseKey", ctx)
	ret0, _ := ret[0].(*types.LicenseKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLicenseKey indicates an expected call of GetLicenseKey.
func (mr *MockStoreMockRecorder) GetLicenseKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLicenseKey", reflect.TypeOf((*MockStore)(nil).GetLicenseKey), ctx)
}

// GetOrganization mocks base method.
func (m *MockStore) GetOrganization(ctx context.Context, q *GetOrganizationQuery) (*types.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganization", ctx, q)
	ret0, _ := ret[0].(*types.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganization indicates an expected call of GetOrganization.
func (mr *MockStoreMockRecorder) GetOrganization(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganization", reflect.TypeOf((*MockStore)(nil).GetOrganization), ctx, q)
}

// GetOrganizationMembership mocks base method.
func (m *MockStore) GetOrganizationMembership(ctx context.Context, q *GetOrganizationMembershipQuery) (*types.OrganizationMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationMembership", ctx, q)
	ret0, _ := ret[0].(*types.OrganizationMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationMembership indicates an expected call of GetOrganizationMembership.
func (mr *MockStoreMockRecorder) GetOrganizationMembership(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationMembership", reflect.TypeOf((*MockStore)(nil).GetOrganizationMembership), ctx, q)
}

// GetProviderEndpoint mocks base method.
func (m *MockStore) GetProviderEndpoint(ctx context.Context, q *GetProviderEndpointsQuery) (*types.ProviderEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderEndpoint", ctx, q)
	ret0, _ := ret[0].(*types.ProviderEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProviderEndpoint indicates an expected call of GetProviderEndpoint.
func (mr *MockStoreMockRecorder) GetProviderEndpoint(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderEndpoint", reflect.TypeOf((*MockStore)(nil).GetProviderEndpoint), ctx, q)
}

// GetRole mocks base method.
func (m *MockStore) GetRole(ctx context.Context, id string) (*types.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", ctx, id)
	ret0, _ := ret[0].(*types.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockStoreMockRecorder) GetRole(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockStore)(nil).GetRole), ctx, id)
}

// GetSecret mocks base method.
func (m *MockStore) GetSecret(ctx context.Context, id string) (*types.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret", ctx, id)
	ret0, _ := ret[0].(*types.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockStoreMockRecorder) GetSecret(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockStore)(nil).GetSecret), ctx, id)
}

// GetSession mocks base method.
func (m *MockStore) GetSession(ctx context.Context, id string) (*types.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, id)
	ret0, _ := ret[0].(*types.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockStoreMockRecorder) GetSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockStore)(nil).GetSession), ctx, id)
}

// GetSessions mocks base method.
func (m *MockStore) GetSessions(ctx context.Context, query GetSessionsQuery) ([]*types.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessions", ctx, query)
	ret0, _ := ret[0].([]*types.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessions indicates an expected call of GetSessions.
func (mr *MockStoreMockRecorder) GetSessions(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessions", reflect.TypeOf((*MockStore)(nil).GetSessions), ctx, query)
}

// GetSessionsCounter mocks base method.
func (m *MockStore) GetSessionsCounter(ctx context.Context, query GetSessionsQuery) (*types.Counter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionsCounter", ctx, query)
	ret0, _ := ret[0].(*types.Counter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionsCounter indicates an expected call of GetSessionsCounter.
func (mr *MockStoreMockRecorder) GetSessionsCounter(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionsCounter", reflect.TypeOf((*MockStore)(nil).GetSessionsCounter), ctx, query)
}

// GetTeam mocks base method.
func (m *MockStore) GetTeam(ctx context.Context, q *GetTeamQuery) (*types.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", ctx, q)
	ret0, _ := ret[0].(*types.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockStoreMockRecorder) GetTeam(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockStore)(nil).GetTeam), ctx, q)
}

// GetTool mocks base method.
func (m *MockStore) GetTool(ctx context.Context, id string) (*types.Tool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTool", ctx, id)
	ret0, _ := ret[0].(*types.Tool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTool indicates an expected call of GetTool.
func (mr *MockStoreMockRecorder) GetTool(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTool", reflect.TypeOf((*MockStore)(nil).GetTool), ctx, id)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(ctx context.Context, q *GetUserQuery) (*types.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, q)
	ret0, _ := ret[0].(*types.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), ctx, q)
}

// GetUserMeta mocks base method.
func (m *MockStore) GetUserMeta(ctx context.Context, id string) (*types.UserMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserMeta", ctx, id)
	ret0, _ := ret[0].(*types.UserMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserMeta indicates an expected call of GetUserMeta.
func (mr *MockStoreMockRecorder) GetUserMeta(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserMeta", reflect.TypeOf((*MockStore)(nil).GetUserMeta), ctx, id)
}

// ListAPIKeys mocks base method.
func (m *MockStore) ListAPIKeys(ctx context.Context, query *ListAPIKeysQuery) ([]*types.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAPIKeys", ctx, query)
	ret0, _ := ret[0].([]*types.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAPIKeys indicates an expected call of ListAPIKeys.
func (mr *MockStoreMockRecorder) ListAPIKeys(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAPIKeys", reflect.TypeOf((*MockStore)(nil).ListAPIKeys), ctx, query)
}

// ListAccessGrants mocks base method.
func (m *MockStore) ListAccessGrants(ctx context.Context, q *ListAccessGrantsQuery) ([]*types.AccessGrant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessGrants", ctx, q)
	ret0, _ := ret[0].([]*types.AccessGrant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessGrants indicates an expected call of ListAccessGrants.
func (mr *MockStoreMockRecorder) ListAccessGrants(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessGrants", reflect.TypeOf((*MockStore)(nil).ListAccessGrants), ctx, q)
}

// ListApps mocks base method.
func (m *MockStore) ListApps(ctx context.Context, q *ListAppsQuery) ([]*types.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApps", ctx, q)
	ret0, _ := ret[0].([]*types.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApps indicates an expected call of ListApps.
func (mr *MockStoreMockRecorder) ListApps(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApps", reflect.TypeOf((*MockStore)(nil).ListApps), ctx, q)
}

// ListDataEntities mocks base method.
func (m *MockStore) ListDataEntities(ctx context.Context, q *ListDataEntitiesQuery) ([]*types.DataEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDataEntities", ctx, q)
	ret0, _ := ret[0].([]*types.DataEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDataEntities indicates an expected call of ListDataEntities.
func (mr *MockStoreMockRecorder) ListDataEntities(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDataEntities", reflect.TypeOf((*MockStore)(nil).ListDataEntities), ctx, q)
}

// ListKnowledge mocks base method.
func (m *MockStore) ListKnowledge(ctx context.Context, q *ListKnowledgeQuery) ([]*types.Knowledge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledge", ctx, q)
	ret0, _ := ret[0].([]*types.Knowledge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKnowledge indicates an expected call of ListKnowledge.
func (mr *MockStoreMockRecorder) ListKnowledge(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledge", reflect.TypeOf((*MockStore)(nil).ListKnowledge), ctx, q)
}

// ListKnowledgeVersions mocks base method.
func (m *MockStore) ListKnowledgeVersions(ctx context.Context, q *ListKnowledgeVersionQuery) ([]*types.KnowledgeVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeVersions", ctx, q)
	ret0, _ := ret[0].([]*types.KnowledgeVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKnowledgeVersions indicates an expected call of ListKnowledgeVersions.
func (mr *MockStoreMockRecorder) ListKnowledgeVersions(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeVersions", reflect.TypeOf((*MockStore)(nil).ListKnowledgeVersions), ctx, q)
}

// ListLLMCalls mocks base method.
func (m *MockStore) ListLLMCalls(ctx context.Context, q *ListLLMCallsQuery) ([]*types.LLMCall, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLLMCalls", ctx, q)
	ret0, _ := ret[0].([]*types.LLMCall)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLLMCalls indicates an expected call of ListLLMCalls.
func (mr *MockStoreMockRecorder) ListLLMCalls(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLLMCalls", reflect.TypeOf((*MockStore)(nil).ListLLMCalls), ctx, q)
}

// ListOrganizationMemberships mocks base method.
func (m *MockStore) ListOrganizationMemberships(ctx context.Context, query *ListOrganizationMembershipsQuery) ([]*types.OrganizationMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizationMemberships", ctx, query)
	ret0, _ := ret[0].([]*types.OrganizationMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationMemberships indicates an expected call of ListOrganizationMemberships.
func (mr *MockStoreMockRecorder) ListOrganizationMemberships(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationMemberships", reflect.TypeOf((*MockStore)(nil).ListOrganizationMemberships), ctx, query)
}

// ListOrganizations mocks base method.
func (m *MockStore) ListOrganizations(ctx context.Context, query *ListOrganizationsQuery) ([]*types.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizations", ctx, query)
	ret0, _ := ret[0].([]*types.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizations indicates an expected call of ListOrganizations.
func (mr *MockStoreMockRecorder) ListOrganizations(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizations", reflect.TypeOf((*MockStore)(nil).ListOrganizations), ctx, query)
}

// ListProviderEndpoints mocks base method.
func (m *MockStore) ListProviderEndpoints(ctx context.Context, q *ListProviderEndpointsQuery) ([]*types.ProviderEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProviderEndpoints", ctx, q)
	ret0, _ := ret[0].([]*types.ProviderEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProviderEndpoints indicates an expected call of ListProviderEndpoints.
func (mr *MockStoreMockRecorder) ListProviderEndpoints(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProviderEndpoints", reflect.TypeOf((*MockStore)(nil).ListProviderEndpoints), ctx, q)
}

// ListRoles mocks base method.
func (m *MockStore) ListRoles(ctx context.Context, organizationID string) ([]*types.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx, organizationID)
	ret0, _ := ret[0].([]*types.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockStoreMockRecorder) ListRoles(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockStore)(nil).ListRoles), ctx, organizationID)
}

// ListScriptRuns mocks base method.
func (m *MockStore) ListScriptRuns(ctx context.Context, q *types.GptScriptRunsQuery) ([]*types.ScriptRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScriptRuns", ctx, q)
	ret0, _ := ret[0].([]*types.ScriptRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScriptRuns indicates an expected call of ListScriptRuns.
func (mr *MockStoreMockRecorder) ListScriptRuns(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScriptRuns", reflect.TypeOf((*MockStore)(nil).ListScriptRuns), ctx, q)
}

// ListSecrets mocks base method.
func (m *MockStore) ListSecrets(ctx context.Context, q *ListSecretsQuery) ([]*types.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSecrets", ctx, q)
	ret0, _ := ret[0].([]*types.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSecrets indicates an expected call of ListSecrets.
func (mr *MockStoreMockRecorder) ListSecrets(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecrets", reflect.TypeOf((*MockStore)(nil).ListSecrets), ctx, q)
}

// ListTeams mocks base method.
func (m *MockStore) ListTeams(ctx context.Context, query *ListTeamsQuery) ([]*types.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTeams", ctx, query)
	ret0, _ := ret[0].([]*types.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTeams indicates an expected call of ListTeams.
func (mr *MockStoreMockRecorder) ListTeams(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTeams", reflect.TypeOf((*MockStore)(nil).ListTeams), ctx, query)
}

// ListTools mocks base method.
func (m *MockStore) ListTools(ctx context.Context, q *ListToolsQuery) ([]*types.Tool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTools", ctx, q)
	ret0, _ := ret[0].([]*types.Tool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTools indicates an expected call of ListTools.
func (mr *MockStoreMockRecorder) ListTools(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTools", reflect.TypeOf((*MockStore)(nil).ListTools), ctx, q)
}

// ListUsers mocks base method.
func (m *MockStore) ListUsers(ctx context.Context, query *ListUsersQuery) ([]*types.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, query)
	ret0, _ := ret[0].([]*types.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockStoreMockRecorder) ListUsers(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockStore)(nil).ListUsers), ctx, query)
}

// LookupKnowledge mocks base method.
func (m *MockStore) LookupKnowledge(ctx context.Context, q *LookupKnowledgeQuery) (*types.Knowledge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupKnowledge", ctx, q)
	ret0, _ := ret[0].(*types.Knowledge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupKnowledge indicates an expected call of LookupKnowledge.
func (mr *MockStoreMockRecorder) LookupKnowledge(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupKnowledge", reflect.TypeOf((*MockStore)(nil).LookupKnowledge), ctx, q)
}

// SetLicenseKey mocks base method.
func (m *MockStore) SetLicenseKey(ctx context.Context, licenseKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLicenseKey", ctx, licenseKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLicenseKey indicates an expected call of SetLicenseKey.
func (mr *MockStoreMockRecorder) SetLicenseKey(ctx, licenseKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLicenseKey", reflect.TypeOf((*MockStore)(nil).SetLicenseKey), ctx, licenseKey)
}

// UpdateApp mocks base method.
func (m *MockStore) UpdateApp(ctx context.Context, tool *types.App) (*types.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateApp", ctx, tool)
	ret0, _ := ret[0].(*types.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateApp indicates an expected call of UpdateApp.
func (mr *MockStoreMockRecorder) UpdateApp(ctx, tool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateApp", reflect.TypeOf((*MockStore)(nil).UpdateApp), ctx, tool)
}

// UpdateDataEntity mocks base method.
func (m *MockStore) UpdateDataEntity(ctx context.Context, dataEntity *types.DataEntity) (*types.DataEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataEntity", ctx, dataEntity)
	ret0, _ := ret[0].(*types.DataEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDataEntity indicates an expected call of UpdateDataEntity.
func (mr *MockStoreMockRecorder) UpdateDataEntity(ctx, dataEntity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataEntity", reflect.TypeOf((*MockStore)(nil).UpdateDataEntity), ctx, dataEntity)
}

// UpdateKnowledge mocks base method.
func (m *MockStore) UpdateKnowledge(ctx context.Context, knowledge *types.Knowledge) (*types.Knowledge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKnowledge", ctx, knowledge)
	ret0, _ := ret[0].(*types.Knowledge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKnowledge indicates an expected call of UpdateKnowledge.
func (mr *MockStoreMockRecorder) UpdateKnowledge(ctx, knowledge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKnowledge", reflect.TypeOf((*MockStore)(nil).UpdateKnowledge), ctx, knowledge)
}

// UpdateKnowledgeState mocks base method.
func (m *MockStore) UpdateKnowledgeState(ctx context.Context, id string, state types.KnowledgeState, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKnowledgeState", ctx, id, state, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateKnowledgeState indicates an expected call of UpdateKnowledgeState.
func (mr *MockStoreMockRecorder) UpdateKnowledgeState(ctx, id, state, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKnowledgeState", reflect.TypeOf((*MockStore)(nil).UpdateKnowledgeState), ctx, id, state, message)
}

// UpdateOrganization mocks base method.
func (m *MockStore) UpdateOrganization(ctx context.Context, org *types.Organization) (*types.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganization", ctx, org)
	ret0, _ := ret[0].(*types.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganization indicates an expected call of UpdateOrganization.
func (mr *MockStoreMockRecorder) UpdateOrganization(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganization", reflect.TypeOf((*MockStore)(nil).UpdateOrganization), ctx, org)
}

// UpdateOrganizationMembership mocks base method.
func (m *MockStore) UpdateOrganizationMembership(ctx context.Context, membership *types.OrganizationMembership) (*types.OrganizationMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganizationMembership", ctx, membership)
	ret0, _ := ret[0].(*types.OrganizationMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganizationMembership indicates an expected call of UpdateOrganizationMembership.
func (mr *MockStoreMockRecorder) UpdateOrganizationMembership(ctx, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganizationMembership", reflect.TypeOf((*MockStore)(nil).UpdateOrganizationMembership), ctx, membership)
}

// UpdateProviderEndpoint mocks base method.
func (m *MockStore) UpdateProviderEndpoint(ctx context.Context, providerEndpoint *types.ProviderEndpoint) (*types.ProviderEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProviderEndpoint", ctx, providerEndpoint)
	ret0, _ := ret[0].(*types.ProviderEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProviderEndpoint indicates an expected call of UpdateProviderEndpoint.
func (mr *MockStoreMockRecorder) UpdateProviderEndpoint(ctx, providerEndpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProviderEndpoint", reflect.TypeOf((*MockStore)(nil).UpdateProviderEndpoint), ctx, providerEndpoint)
}

// UpdateRole mocks base method.
func (m *MockStore) UpdateRole(ctx context.Context, role *types.Role) (*types.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, role)
	ret0, _ := ret[0].(*types.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockStoreMockRecorder) UpdateRole(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockStore)(nil).UpdateRole), ctx, role)
}

// UpdateSecret mocks base method.
func (m *MockStore) UpdateSecret(ctx context.Context, secret *types.Secret) (*types.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, secret)
	ret0, _ := ret[0].(*types.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockStoreMockRecorder) UpdateSecret(ctx, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockStore)(nil).UpdateSecret), ctx, secret)
}

// UpdateSession mocks base method.
func (m *MockStore) UpdateSession(ctx context.Context, session types.Session) (*types.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, session)
	ret0, _ := ret[0].(*types.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockStoreMockRecorder) UpdateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockStore)(nil).UpdateSession), ctx, session)
}

// UpdateSessionMeta mocks base method.
func (m *MockStore) UpdateSessionMeta(ctx context.Context, data types.SessionMetaUpdate) (*types.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionMeta", ctx, data)
	ret0, _ := ret[0].(*types.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSessionMeta indicates an expected call of UpdateSessionMeta.
func (mr *MockStoreMockRecorder) UpdateSessionMeta(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionMeta", reflect.TypeOf((*MockStore)(nil).UpdateSessionMeta), ctx, data)
}

// UpdateSessionName mocks base method.
func (m *MockStore) UpdateSessionName(ctx context.Context, sessionID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionName", ctx, sessionID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionName indicates an expected call of UpdateSessionName.
func (mr *MockStoreMockRecorder) UpdateSessionName(ctx, sessionID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionName", reflect.TypeOf((*MockStore)(nil).UpdateSessionName), ctx, sessionID, name)
}

// UpdateTeam mocks base method.
func (m *MockStore) UpdateTeam(ctx context.Context, team *types.Team) (*types.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeam", ctx, team)
	ret0, _ := ret[0].(*types.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTeam indicates an expected call of UpdateTeam.
func (mr *MockStoreMockRecorder) UpdateTeam(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeam", reflect.TypeOf((*MockStore)(nil).UpdateTeam), ctx, team)
}

// UpdateTool mocks base method.
func (m *MockStore) UpdateTool(ctx context.Context, tool *types.Tool) (*types.Tool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTool", ctx, tool)
	ret0, _ := ret[0].(*types.Tool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTool indicates an expected call of UpdateTool.
func (mr *MockStoreMockRecorder) UpdateTool(ctx, tool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTool", reflect.TypeOf((*MockStore)(nil).UpdateTool), ctx, tool)
}

// UpdateUser mocks base method.
func (m *MockStore) UpdateUser(ctx context.Context, user *types.User) (*types.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(*types.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreMockRecorder) UpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), ctx, user)
}

// UpdateUserMeta mocks base method.
func (m *MockStore) UpdateUserMeta(ctx context.Context, UserMeta types.UserMeta) (*types.UserMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserMeta", ctx, UserMeta)
	ret0, _ := ret[0].(*types.UserMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserMeta indicates an expected call of UpdateUserMeta.
func (mr *MockStoreMockRecorder) UpdateUserMeta(ctx, UserMeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserMeta", reflect.TypeOf((*MockStore)(nil).UpdateUserMeta), ctx, UserMeta)
}

// MockEmbeddingsStore is a mock of EmbeddingsStore interface.
type MockEmbeddingsStore struct {
	ctrl     *gomock.Controller
	recorder *MockEmbeddingsStoreMockRecorder
	isgomock struct{}
}

// MockEmbeddingsStoreMockRecorder is the mock recorder for MockEmbeddingsStore.
type MockEmbeddingsStoreMockRecorder struct {
	mock *MockEmbeddingsStore
}

// NewMockEmbeddingsStore creates a new mock instance.
func NewMockEmbeddingsStore(ctrl *gomock.Controller) *MockEmbeddingsStore {
	mock := &MockEmbeddingsStore{ctrl: ctrl}
	mock.recorder = &MockEmbeddingsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbeddingsStore) EXPECT() *MockEmbeddingsStoreMockRecorder {
	return m.recorder
}

// CreateKnowledgeEmbedding mocks base method.
func (m *MockEmbeddingsStore) CreateKnowledgeEmbedding(ctx context.Context, embeddings ...*types.KnowledgeEmbeddingItem) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range embeddings {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateKnowledgeEmbedding", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateKnowledgeEmbedding indicates an expected call of CreateKnowledgeEmbedding.
func (mr *MockEmbeddingsStoreMockRecorder) CreateKnowledgeEmbedding(ctx any, embeddings ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, embeddings...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKnowledgeEmbedding", reflect.TypeOf((*MockEmbeddingsStore)(nil).CreateKnowledgeEmbedding), varargs...)
}

// DeleteKnowledgeEmbedding mocks base method.
func (m *MockEmbeddingsStore) DeleteKnowledgeEmbedding(ctx context.Context, knowledgeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKnowledgeEmbedding", ctx, knowledgeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKnowledgeEmbedding indicates an expected call of DeleteKnowledgeEmbedding.
func (mr *MockEmbeddingsStoreMockRecorder) DeleteKnowledgeEmbedding(ctx, knowledgeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKnowledgeEmbedding", reflect.TypeOf((*MockEmbeddingsStore)(nil).DeleteKnowledgeEmbedding), ctx, knowledgeID)
}

// QueryKnowledgeEmbeddings mocks base method.
func (m *MockEmbeddingsStore) QueryKnowledgeEmbeddings(ctx context.Context, q *types.KnowledgeEmbeddingQuery) ([]*types.KnowledgeEmbeddingItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryKnowledgeEmbeddings", ctx, q)
	ret0, _ := ret[0].([]*types.KnowledgeEmbeddingItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryKnowledgeEmbeddings indicates an expected call of QueryKnowledgeEmbeddings.
func (mr *MockEmbeddingsStoreMockRecorder) QueryKnowledgeEmbeddings(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryKnowledgeEmbeddings", reflect.TypeOf((*MockEmbeddingsStore)(nil).QueryKnowledgeEmbeddings), ctx, q)
}
