package prompts

import "fmt"

// RegisterBuiltins registers every prompt that ships with helix-org.
// Mirror of tools.RegisterBuiltins: one place to add a new prompt and
// everything else (per-worker MCP exposure, chat slash-command
// expansion, /help listing) picks it up for free.
//
// Help is registered last so it sees every sibling prompt — its
// listing is generated by walking the registry at invocation time,
// which only works if the siblings are already in there.
func RegisterBuiltins(reg *Registry) error {
	for _, p := range []Prompt{
		Role{},
		PMBot{},
	} {
		if err := reg.Register(p); err != nil {
			return fmt.Errorf("register %q: %w", p.Name(), err)
		}
	}
	if err := reg.Register(NewHelp(reg)); err != nil {
		return fmt.Errorf("register %q: %w", HelpName, err)
	}
	return nil
}
