// Code generated by MockGen. DO NOT EDIT.
// Source: helix_code_review.go
//
// Generated by this command:
//
//	mockgen -source helix_code_review.go -destination controller_mocks.go -package project
//

// Package project is a generated GoMock package.
package project

import (
	context "context"
	reflect "reflect"

	controller "github.com/helixml/helix/api/pkg/controller"
	types "github.com/helixml/helix/api/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// RunBlockingSession mocks base method.
func (m *MockController) RunBlockingSession(ctx context.Context, req *controller.RunSessionRequest) (*types.Interaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunBlockingSession", ctx, req)
	ret0, _ := ret[0].(*types.Interaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunBlockingSession indicates an expected call of RunBlockingSession.
func (mr *MockControllerMockRecorder) RunBlockingSession(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunBlockingSession", reflect.TypeOf((*MockController)(nil).RunBlockingSession), ctx, req)
}

// WriteSession mocks base method.
func (m *MockController) WriteSession(ctx context.Context, session *types.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteSession indicates an expected call of WriteSession.
func (mr *MockControllerMockRecorder) WriteSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteSession", reflect.TypeOf((*MockController)(nil).WriteSession), ctx, session)
}
