version: "2"

run:
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - copyloopvar
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    rules:
      - path: "api/*"
        linters:
          - lll
      - path: "internal/*"
        linters:
          - dupl
          - lll

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  revive:
    rules:
      - name: comment-spacings
