version: "2"

run:
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - copyloopvar
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    rules:
      - path: "api/*"
        linters:
          - lll
      - path: "internal/*"
        linters:
          - dupl
          - lll
      # Dot imports are standard for ginkgo/gomega in k8s operator tests
      - path: "test/"
        linters:
          - revive
          - staticcheck
      - path: "_test\\.go"
        linters:
          - revive
          - staticcheck

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  revive:
    rules:
      - name: comment-spacings
      # Disable dot-imports rule - standard for ginkgo/gomega
      - name: dot-imports
        disabled: true
      # Disable var-naming for test utils package
      - name: var-naming
        disabled: true
