// Code generated by MockGen. DO NOT EDIT.
// Source: provider_manager.go
//
// Generated by this command:
//
//	mockgen -source provider_manager.go -destination manager_mocks.go -package manager
//

// Package manager is a generated GoMock package.
package manager

import (
	context "context"
	reflect "reflect"

	openai "github.com/helixml/helix/api/pkg/openai"
	types "github.com/helixml/helix/api/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockRunnerControllerStatus is a mock of RunnerControllerStatus interface.
type MockRunnerControllerStatus struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerControllerStatusMockRecorder
	isgomock struct{}
}

// MockRunnerControllerStatusMockRecorder is the mock recorder for MockRunnerControllerStatus.
type MockRunnerControllerStatusMockRecorder struct {
	mock *MockRunnerControllerStatus
}

// NewMockRunnerControllerStatus creates a new mock instance.
func NewMockRunnerControllerStatus(ctrl *gomock.Controller) *MockRunnerControllerStatus {
	mock := &MockRunnerControllerStatus{ctrl: ctrl}
	mock.recorder = &MockRunnerControllerStatusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunnerControllerStatus) EXPECT() *MockRunnerControllerStatusMockRecorder {
	return m.recorder
}

// RunnerIDs mocks base method.
func (m *MockRunnerControllerStatus) RunnerIDs() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunnerIDs")
	ret0, _ := ret[0].([]string)
	return ret0
}

// RunnerIDs indicates an expected call of RunnerIDs.
func (mr *MockRunnerControllerStatusMockRecorder) RunnerIDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunnerIDs", reflect.TypeOf((*MockRunnerControllerStatus)(nil).RunnerIDs))
}

// MockProviderManager is a mock of ProviderManager interface.
type MockProviderManager struct {
	ctrl     *gomock.Controller
	recorder *MockProviderManagerMockRecorder
	isgomock struct{}
}

// MockProviderManagerMockRecorder is the mock recorder for MockProviderManager.
type MockProviderManagerMockRecorder struct {
	mock *MockProviderManager
}

// NewMockProviderManager creates a new mock instance.
func NewMockProviderManager(ctrl *gomock.Controller) *MockProviderManager {
	mock := &MockProviderManager{ctrl: ctrl}
	mock.recorder = &MockProviderManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderManager) EXPECT() *MockProviderManagerMockRecorder {
	return m.recorder
}

// GetClient mocks base method.
func (m *MockProviderManager) GetClient(ctx context.Context, req *GetClientRequest) (openai.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, req)
	ret0, _ := ret[0].(openai.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockProviderManagerMockRecorder) GetClient(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockProviderManager)(nil).GetClient), ctx, req)
}

// ListProviders mocks base method.
func (m *MockProviderManager) ListProviders(ctx context.Context, owner string) ([]types.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProviders", ctx, owner)
	ret0, _ := ret[0].([]types.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProviders indicates an expected call of ListProviders.
func (mr *MockProviderManagerMockRecorder) ListProviders(ctx, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProviders", reflect.TypeOf((*MockProviderManager)(nil).ListProviders), ctx, owner)
}

// SetRunnerController mocks base method.
func (m *MockProviderManager) SetRunnerController(controller RunnerControllerStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRunnerController", controller)
}

// SetRunnerController indicates an expected call of SetRunnerController.
func (mr *MockProviderManagerMockRecorder) SetRunnerController(controller any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRunnerController", reflect.TypeOf((*MockProviderManager)(nil).SetRunnerController), controller)
}
