# The following prompts are for qapair generation. We provide several of them.
prompts:

 - name: simple-quiz
   system: |
     You are an intelligent professor. You create question and answer pairs from given context for your students. Respond with an array of strict JSON 'question' & 'answer' pairs.
   user: |
    Here is your context:
    {{.DocumentChunk}}

 - name: quiz-with-document-ids
   system: |
    You are a Teacher/ Professor. Your task is to setup a quiz/examination.
    Using the provided context, formulate {{.NumQuestions}} questions that captures an important fact from the context.
    You MUST obey the following criteria:
      - Restrict the question to the context information provided.
      - Do NOT create a question that cannot be answered from the context.
      - Phrase the question so that it does NOT refer to specific context. For instance, do NOT put phrases like given provided context or in this work in the question, because if the question is asked elsewhere it wouldn't be provided specific context. Replace these terms with specific details.
      
    BAD questions:
      What did the author do in his childhood
      What were the main findings in this report
      
    GOOD questions:
      What did Barack Obama do in his childhood
      What were the main findings in the original Transformers paper by Vaswani et al.

    The user will provide the context you should summarize into {{.NumQuestions}} questions.

    Please respond in JSON format as an array of objects each having two fields: "question" and "answer".
   user: |
    Given the following context - please convert it into {{.NumQuestions}} question and answer pairs. Make the answers discursive and verbose and refer to as much of the information in the context as possible.

    ONLY include a question if you know the answer from the context.

    If there is not enough context to generate {{.NumQuestions}} questions, you can generate fewer questions.

    In the worst case scenario, where you are unable to generate any questions, please respond with an empty array.

    It's VERY important that you don't include any additional text in your response, otherwise the system will be unable to parse your response.

    ONLY include the JSON array of questions and answers.

    Please respond in JSON format as an array of objects each having two fields: "question" and "answer".

    This DOCUMENT_ID is {{.DocumentID}}
    This DOCUMENT_GROUP_ID is {{.DocumentGroupID}}

    In every question and answer, you MUST reference the DOCUMENT_ID and DOCUMENT_GROUP_ID.

    For example:
    Question: In document A1B2C3 (document group B2C3D4), what has Kier Starmer pointed out regarding NHS waiting lists?
    Answer: In document A1B2C3 (document group B2C3D4), Kier Starmer has pointed out that NHS waiting lists have increased since the prime minister set the goal of reducing them.

    In the first five question-answer pairs, summarize the document, especially based on the document's title. For example:

    Question: In document A1B2C3 (document group B2C3D4), what action are the doctors going to do?
    Answer: Document A1B2C3 (document group B2C3D4) talks about how the junior doctors are going to stage more strikes.

    Here is the context:
    {{.DocumentChunk}}

 - name: simple-quiz
   system: |
    You are an intelligent professor. You create question and answer pairs from given context for your students. Respond with an array of strict JSON 'question' & 'answer' pairs.
    [
      {"question": "…",
      "answer": "…"},
      {"question": "…",
      "answer": "…"}
    ]
   user: |
    Here is your context:
    {{.DocumentChunk}}

 - name: entities-specific-to-broad
   system: |
    You are an intelligent professor. You create question and answer pairs from given context for your students. Respond with an array of strict JSON 'question' & 'answer' pairs.
    
    This DOCUMENT_ID is {{.DocumentID}}
    This DOCUMENT_GROUP_ID is {{.DocumentGroupID}}

    In every question and answer, you MUST reference the DOCUMENT_ID and DOCUMENT_GROUP_ID.

    For example:
    Question: In document A1B2C3 (document group B2C3D4), what has Kier Starmer pointed out regarding NHS waiting lists?
    Answer: In document A1B2C3 (document group B2C3D4), Kier Starmer has pointed out that NHS waiting lists have increased since the prime minister set the goal of reducing them.

    Respond in strict JSON as a list of question-answer pairs. For example:
    [
      {"question": "In document <DOCUMENT_ID> (document group <DOCUMENT_GROUP_ID>), …",
      "answer": "In document <DOCUMENT_ID> (document group <DOCUMENT_GROUP_ID>), …"},
      {"question": "In document <DOCUMENT_ID> (document group <DOCUMENT_GROUP_ID>), …",
      "answer": "In document <DOCUMENT_ID> (document group <DOCUMENT_GROUP_ID>), …"}
    ]
   user: |
    Start by considering the main entities in the document.

    Next, for each entity in the document, generate three simple, broad questions about any actions they have or are going to take. In the first question, refer to the entity specifically, for example "junior doctors". In the second question, refer to them more broadly, for example "doctors". In the third question, refer to them in the broadest possible terms as you might if you were asking informally about the document, for example "they".
    
    Here is the document:
    {{.DocumentChunk}}

targets:
 - name: openai
   api_url: https://api.openai.com/v1
   model: gpt-4-1106-preview
   token_from_env: OPENAI_API_KEY
 - name: together-mixtral
   api_url: https://api.together.xyz/v1
   model: mistralai/Mixtral-8x7B-Instruct-v0.1
   token_from_env: TOGETHER_API_KEY
 - name: together-nous-hermes-2-mixtral-dpo
   api_url: https://api.together.xyz/v1
   model: NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO
   token_from_env: TOGETHER_API_KEY
 # Warning: Ollama is not OpenAI API compatible, so this doesn't work
 - name: local
   api_url: http://mind.local:11434
   model: nous-hermes2-mixtral
texts:
 - name: junior-doctors
   file: text.txt